"""
Bot Configuration — All settings, messages, and question banks.
Edit this file to customize the bot's behavior and content.
"""

# ==================== SETTINGS ====================

TIMEZONE = "Asia/Manila"

# Chatter reward time (Manila time). Daily questions use auto-rotation (24h / question count).
CHATTER_SCHEDULE = {"hour": 23, "minute": 59}

CHIPS = {
    "name": "chips",
    "emoji": "🥔",
    "singular": "chip",
    "plural": "chips",
    "rewards": {
        "top_chatter": 10,
        "second_chatter": 5,
        "chip_drop": 10,
    },
}

CHIP_DROP = {
    "min_interval": 1,    # minutes between drops (minimum)
    "max_interval": 5,    # minutes between drops (maximum)
    "button_timeout": 900, # seconds before drop expires (15 min)
}

CODE_PURPLE = {
    "inactivity_hours": 6,
    "cooldown_hours": 24,
}

FEATURES = {
    "typology": True,
    "casual": True,
    "personality": True,
    "chatter_rewards": True,
    "chip_drops": True,
    "code_purple": True,
}

LEADERBOARD = {
    "page_size": 10,
}

# ==================== EMBED CONFIG ====================

AUTHOR_NAME = "CRISPS GC ✶⋆.˚🥔"

# Colors as hex WITHOUT the # prefix (used with int(x, 16))
COLORS = {
    "typology": "FFD700",
    "casual": "FF69B4",
    "personality": "9B59B6",
    "leaderboard": "FF8C00",
}

EMBEDS = {
    "typology": {
        "title": "✨ Daily Typology Question",
        "footer": "Drop your thoughts below 💭",
    },
    "casual": {
        "title": "💬 Casual Question Daily",
        "footer": "Drop your thoughts below 💭",
    },
    "personality": {
        "title": "🧠 Daily Personality Question",
        "footer": "Drop your thoughts below 💭",
    },
    "leaderboard": {
        "title": "🏆 Chip Leaderboard",
        "footer": "Use /balance to check yours",
        "rank_emojis": {"1": "🥇", "2": "🥈", "3": "🥉", "default": "🔹"},
    },
}

# ==================== MESSAGES ====================

MESSAGES = {
    "chip_drop": {
        "announcements": [
            "A wild chip drop appears! First to grab gets **+{amount} {emoji}**",
            "Free chips up for grabs! Be the first to claim **+{amount} {emoji}**",
            "🥔 Dropping some free chips real quick... grab it before someone else does!",
            "🥔 Random chip drop event! Grab it before it's gone :)",
        ],
        "claimed": [
            "**{user}** was first to snatch **+{amount} {emoji}**",
            "Nice! **{user}** just grabbed **+{amount} {emoji}**",
            "**{user}** swooped in and claimed **+{amount} {emoji}**",
        ],
        "expired": [
            "...Nobody claimed them. They're gone now",
            "Chips expired. Maybe next time...",
            "Too late, they're gone",
            "And... nobody grabbed them. Rip chips :(",
        ],
    },
    "code_purple": [
        "Code purple...",
        "...code purple?",
        "helloooo? anyone there? code purple guysss...",
        "Ehem...... **taps mic** code purple.",
        "Somebody say something in the server challenge (IMPOSSIBLE!!) (NOT CLICKBAIT!)",
        "The silence is deafening... code purple",
        "...y'all alive? code purple...",
        "# Code Purple.",
        "no one has chatted in a while... code purple :(",
        "anyone there? code purple",
        "I'm just a bot no one appreciates :(",
        "-# code purple... anyone? :(",
    ],
    "chatter_reward": {
        "announcement": "**Daily Chatter Rewards 💬**",
        "top_chatter": "**{user}** talked the most today — **+{amount} {emoji}**",
        "second_chatter": "**{user}** came second — **+{amount} {emoji}**",
        "no_activity": "Nobody chatted today. No rewards.",
        "same_user": "**{user}** took both spots. **+{amount} {emoji}** total",
    },
    "balance": {
        "response": "You have **{amount} {emoji}** (ranked **{rank}**)",
        "no_balance": "You don't have any chips yet. Chat more 🥔",
        "unranked": "Unranked",
    },
    "leaderboard": {
        "entry": "{emoji} **{rank}.** {user} — **{amount} {currency}**",
        "your_position": "Your position: **#{rank}** with **{amount} {currency}**",
        "empty": "Well... Nobody has chips yet.",
    },
    "errors": {
        "generic": "Something went wrong. Try again later.",
    },
    "success": {
        "force_drop": "Chip drop triggered.",
    },
    "word_game": {
        "started": "🎮 Word game started! Just type a word to add it to the story.",
        "ended": "📖 {user} ended the story! ({count} words total).",
        "word_added": "✓ Added \"{word}\".",
        "already_active": "A word game is already in progress! Use `/wordgame end` to finish it first.",
        "no_game": "No active word game! Start one with `/wordgame start`.",
        "no_game_end": "No active word game to end.",
        "wrong_channel": "Word game is only active in <#{channel}>.",
        "failed": "Failed to start game - check bot permissions.",
        "not_a_word": "That's not a word! Only single words allowed.",
        "not_a_word_snarky": "That's not a word! ...you *do* know how the game works right?",
        "consecutive": "You can't add two words in a row! Let someone else go.",
    },
}

WORD_GAME = {
    "embed": {
        "title": "📖 Word Game",
        "title_ended": "📖 Story Complete!",
        "empty_story": "*Type a word to start the story!*",
        "footer": "One word per message • Punctuation auto-formats",
        "footer_ended": "words total",
        "last_word_by": "Last word by",
        "color": "9B59B6",
    },
}

# ==================== TYPOLOGY ====================

MBTI_TYPES = [
    "INTJ", "INTP", "ENTJ", "ENTP",
    "INFJ", "INFP", "ENFJ", "ENFP",
    "ISTJ", "ISFJ", "ESTJ", "ESFJ",
    "ISTP", "ISFP", "ESTP", "ESFP",
]

ENNEAGRAM_TYPES = [
    "1w9", "1w2", "2w1", "2w3", "3w2", "3w4",
    "4w3", "4w5", "5w4", "5w6", "6w5", "6w7",
    "7w6", "7w8", "8w7", "8w9", "9w8", "9w1",
]

TYPOLOGY_QUESTIONS = [
    "Who would you prefer as your teacher?",
    "Who would you rather hang out with for an entire day?",
    "Who would you trust more to handle conflict in a group setting?",
    "Who would you trust more with a secret?",
    "Who would you rather party with?",
    "Who do you think would win in a debate?",
    "Who would you prefer as your project leader?",
    "Who would you rather go on a road trip with?",
    "Who do you think is more likely to start a business?",
    "Who would you rather go to for life advice?",
    "Who would you rather have as a roommate?",
    "Who do you think would win in a trivia competition?",
    "Who would you trust more to handle stress during a crisis?",
    "Who do you think is more likely to make you laugh?",
    "Who would you trust to plan your birthday party?",
    "Who would you prefer as your therapist?",
    "Who would you rather work on a group project with?",
    "Who do you think would win in a chess match?",
    "Who would you rather travel with internationally?",
    "Who do you think would handle a breakup more gracefully?",
    "Who would you want on your trivia team?",
    "Who would you trust more to negotiate a raise?",
    "Who do you think would win in a cooking competition?",
    "Who would you prefer as your loyal friend?",
    "Who would you rather have as your mentor?",
    "Who would you trust more in awkward social situations?",
    "Who would you prefer for a long-distance friendship?",
    "Who would you trust to give honest feedback?",
    "Who do you think would win at a creative challenge?",
    "Who would you prefer as your creative partner?",
    "Who do you think is more likely to remember your birthday?",
    "Who would you rather debate with?",
    "Who would you prefer to comfort you when sad?",
    "Who do you think would handle rejection more gracefully?",
    "Who would you prefer as your podcast co-host?",
    "Who do you think would win in a physical challenge?",
    "Who would you rather share an apartment with?",
    "Who would you trust more to keep you motivated?",
    "Who would you rather have a prank war with?",
    "Who would you trust to help you move?",
    "Who do you think would win at solving a mystery?",
    "Who would you rather choose as study partners?",
    "Who do you think is more likely to defend you in an argument?",
    "Who would you rather have plan your wedding?",
    "Who would you prefer as your dinner party host?",
    "Who do you think would handle long work hours better?",
    "Who would you trust more with your pet?",
    "Who do you think would win in a survival situation?",
    "Who would you rather have as your backpacking travel companion?",
    "Who would you prefer for support during tough times?",
    "Who do you think would handle sudden change better?",
    "Who would you rather collaborate with on creative work?",
    "Who would you prefer to cheer you up?",
    "Who would you rather have a conversation with?",
    "Who do you think would handle public speaking better?",
    "Who do you think would win at video games?",
    "Who would you rather receive criticism from?",
    "Who would you prefer to organize an event?",
    "Who would you prefer as your emergency contact?",
]

# ==================== SPARK — WOULD YOU RATHER ====================

SPARK_WYR = [
    "Would you rather have the ability to fly but only 3 feet off the ground, or be able to teleport but only to places you've already been?",
    "Would you rather always have to sing instead of speaking, or always have to dance everywhere you go?",
    "Would you rather have unlimited pizza for life or unlimited tacos for life?",
    "Would you rather be able to talk to animals but they're all very rude, or be able to read minds but only hear people's most boring thoughts?",
    "Would you rather have a rewind button for your life or a pause button?",
    "Would you rather always be 10 minutes late or always be 20 minutes early?",
    "Would you rather have a personal chef or a personal chauffeur?",
    "Would you rather give up all drinks except water or give up eating anything that was cooked in an oven?",
    "Would you rather always have to tell the truth or always have to lie?",
    "Would you rather live without music or live without movies?",
    "Would you rather be famous for something you didn't do or be unknown for something amazing you did?",
    "Would you rather have the ability to see 10 minutes into the future or 10 years into the future?",
    "Would you rather have a photographic memory or be able to forget anything you want?",
    "Would you rather have a lifetime supply of your favorite snack or never pay for WiFi again?",
    "Would you rather be able to control fire or water?",
    "Would you rather have all traffic lights be green for you or never have to wait in line again?",
    "Would you rather be able to speak every language fluently or be able to play every musical instrument?",
    "Would you rather only be able to whisper or only be able to shout?",
    "Would you rather have a clone of yourself or a robot assistant?",
    "Would you rather always know when someone is lying or always get away with lying?",
    "Would you rather have super strength or super speed?",
    "Would you rather be able to breathe underwater or fly through the air?",
    "Would you rather have the ability to time travel or the ability to teleport?",
    "Would you rather always feel too hot or always feel too cold?",
    "Would you rather never use social media again or never watch TV/movies again?",
    "Would you rather relive the same day for a year or lose a year of your memory?",
    "Would you rather know all the mysteries of the universe or know your exact future?",
    "Would you rather be able to change the past or see into the future?",
    "Would you rather have no sense of taste or no sense of smell?",
    "Would you rather be stuck in traffic for 2 hours or have a flight delayed by 4 hours?",
    "Would you rather have to wear wet socks every day or wear a wool sweater in summer?",
    "Would you rather live in a world without problems or a world without mysteries?",
    "Would you rather have unlimited books or unlimited movies?",
    "Would you rather be witty in conversations or wise in decisions?",
    "Would you rather explore space or explore the ocean?",
    "Would you rather have breakfast for dinner or dinner for breakfast?",
    "Would you rather win the lottery but lose all your friends or stay as you are?",
    "Would you rather know when you'll die or how you'll die?",
    "Would you rather have more confidence or more competence?",
    "Would you rather live without air conditioning or without heating?",
    "Would you rather always have the hiccups or always have an itch you can't scratch?",
    "Would you rather be able to stop time or fly?",
    "Would you rather have one superpower for a day or none forever?",
    "Would you rather live in a big city or in the countryside?",
    "Would you rather have unlimited first-class tickets or never have to sleep?",
    "Would you rather have a terrible short-term memory or a terrible long-term memory?",
    "Would you rather be feared or loved?",
    "Would you rather have the power to heal yourself or heal others?",
    "Would you rather work alone and get full credit or work in a team and share credit?",
    "Would you rather be the funniest person in the room or the smartest?",
    "Would you rather lose your ability to read or lose your ability to speak?",
    "Would you rather have an unlimited international first-class ticket or never have to pay for food again?",
    "Would you rather be able to control time or control space?",
    "Would you rather have perfect memory or perfect vision of the future?",
    "Would you rather live in a world where everyone tells the truth or where everyone is kind?",
    "Would you rather always be slightly early or slightly late?",
    "Would you rather have more wisdom or more intelligence?",
    "Would you rather be able to read faster or remember more?",
    "Would you rather have hands for feet or feet for hands?",
    "Would you rather lose the ability to lie or believe every lie you're told?",
    "Would you rather have a constantly full battery on your devices or never need gas in your car?",
    "Would you rather give up desserts or give up coffee/tea?",
    "Would you rather be color blind or lose your sense of taste?",
    "Would you rather work a high-paying job you hate or a low-paying job you love?",
    "Would you rather have a beautiful house and ugly car or ugly house and beautiful car?",
    "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?",
    "Would you rather experience every human emotion intensely or feel nothing at all?",
    "Would you rather have to say everything on your mind or never speak again?",
    "Would you rather be famous when you're alive and forgotten when you die or unknown when you're alive but famous after you die?",
    "Would you rather have the ability to speak all human languages or be able to speak to animals?",
    "Would you rather be poor but help people or rich but unable to help anyone?",
    "Would you rather have every day be the same or completely unpredictable?",
    "Would you rather live without emotions or live with uncontrollable emotions?",
    "Would you rather be able to see 10 years into your own future or 10 years into someone else's?",
    "Would you rather have people admire you or understand you?",
    "Would you rather give up reading or give up listening to music?",
    "Would you rather be always overdressed or always underdressed?",
    "Would you rather know every language in the world or every coding language?",
    "Would you rather have a photographic memory of everything you read or everything you see?",
    "Would you rather be extremely lucky but not talented or extremely talented but unlucky?",
    "Would you rather lose all your memories from birth to now or lose the ability to form new memories?",
    "Would you rather be surrounded by people who agree with you or people who challenge you?",
    "Would you rather have the ability to never feel physical pain or never feel emotional pain?",
    "Would you rather be invisible for a day or be able to fly for a day?",
    "Would you rather have a terrible boss but great coworkers or a great boss but terrible coworkers?",
    "Would you rather be able to master every instrument or every sport?",
    "Would you rather have all your meals prepared for you or have someone clean your house every day?",
    "Would you rather have to speak in rhymes or sing everything you say?",
    "Would you rather be able to control your dreams or never need to sleep?",
    "Would you rather always say what you think or never speak your mind?",
    "Would you rather have an easy life with no purpose or a hard life with deep meaning?",
    "Would you rather be trapped in a romantic comedy with your enemies or a horror movie with your friends?",
    "Would you rather only be able to use a fork or only be able to use a spoon?",
    "Would you rather have your life be a constant adventure or a constant comfort?",
    "Would you rather undo your biggest regret or relive your best memory?",
    "Would you rather be the best player on a losing team or the worst player on a winning team?",
    "Would you rather always know what people think of you or never know?",
    "Would you rather live in a utopia as a normal person or in the real world as a superhero?",
    "Would you rather have no privacy but be completely safe or have complete privacy but no security?",
    "Would you rather be remembered for your kindness or your intelligence?",
    "Would you rather have a high IQ or high EQ?",
    "Would you rather be able to predict the weather or predict people's moods?",
    "Would you rather lose your phone for a month or your laptop for a month?",
    "Would you rather always have to enter rooms backwards or always have to somersault out?",
    "Would you rather have a British accent or a French accent?",
    "Would you rather live in a dystopia with people you love or a utopia alone?",
    "Would you rather always be in a crowded room or always be alone?",
    "Would you rather have free Wi-Fi wherever you go or free coffee wherever you go?",
    "Would you rather be able to talk to your past self or your future self?",
    "Would you rather be able to change your appearance at will or change your personality at will?",
    "Would you rather have all the conspiracy theories be true or none of them?",
    "Would you rather have to live without heat in winter or without AC in summer?",
    "Would you rather be stuck on a broken ski lift or stuck in a broken elevator?",
    "Would you rather lose the ability to use your hands or lose the ability to walk?",
    "Would you rather be really good at dancing or really good at singing?",
    "Would you rather live without problems or live without challenges?",
    "Would you rather be forced to live the same day forever or never be able to remember yesterday?",
    "Would you rather have a personal library or a personal movie theater?",
    "Would you rather be able to change one decision from your past or make one guaranteed decision about your future?",
    "Would you rather be the hero who saves everyone but no one knows or the villain everyone fears?",
    "Would you rather be able to control other people's emotions or your own?",
    "Would you rather have everything you touch turn to gold or have the ability to heal anything?",
    "Would you rather live a short life that's exciting or a long life that's boring?",
    "Would you rather have a job that pays well but requires 80 hours a week or one that pays little but requires 20 hours a week?",
    "Would you rather be a character in a horror story or a tragedy?",
    "Would you rather have your thoughts appear as text above your head or have everything you feel appear as emojis above your head?",
    "Would you rather be able to speak to inanimate objects or have them speak to you?",
    "Would you rather lose the ability to cry or cry every time you hear music?",
]

# ==================== SPARK — DEBATES ====================

SPARK_DEBATES = [
    "How many holes does a straw have — one or two?",
    "Is water wet, or does it just make things wet?",
    "Is a hot dog a sandwich?",
    "Is cereal a soup?",
    "Are eyebrows considered facial hair?",
    "Is a thumb a finger?",
    "If you're waiting for the waiter, aren't you the waiter?",
    "Is a taco a sandwich?",
    "Are there more doors or wheels in the world?",
    "Is it pronounced 'GIF' or 'JIF'?",
    "Does pineapple belong on pizza?",
    "Is it better to have more time or more money?",
    "Should toilet paper roll over or under?",
    "Do people change, or do they just become more themselves?",
    "Is it acceptable to double text?",
    "Do experiences or possessions bring more happiness?",
    "Is social media improving or ruining communication?",
    "Is talent natural or developed?",
    "Is it okay to leave a read message unanswered?",
    "Can money buy happiness?",
    "Is love a choice or a feeling?",
    "Is it weird to go to a movie alone?",
    "Is it weird to talk to yourself?",
    "Is forgiveness for the giver or the receiver?",
    "Is it better to be respected or liked?",
    "Do we define our own success, or does society define it?",
    "Is privacy more important than security?",
    "Should you follow your passion or follow the money?",
    "Is it more important to be understood or to understand others?",
    "Can true friendship exist without honesty?",
    "Is ambition a virtue or a vice?",
    "Should you stay loyal to people or to principles?",
    "Is it better to risk failure or guarantee mediocrity?",
    "Does intention matter more than impact?",
    "Is boredom a problem or an opportunity?",
    "Should you adapt to the world or try to change it?",
    "Is comfort the enemy of growth?",
    "Can logic and emotion coexist in decision-making?",
    "Is it better to be remembered for one thing or known for many?",
    "Should you trust your instincts or analyze everything?",
    "Is vulnerability a strength or a risk?",
    "Does everyone deserve a second chance?",
    "Is it more important to fit in or stand out?",
    "Should emotions guide your decisions or should you suppress them?",
    "Is self-improvement selfish?",
    "Can you truly know someone?",
    "Is honesty always the best policy?",
    "Should you prioritize logic or empathy when helping someone?",
    "Is nostalgia helpful or harmful?",
    "Are people inherently good or inherently selfish?",
    "Should you speak up even when it's uncomfortable?",
    "Is consistency more important than flexibility?",
    "Can freedom exist without responsibility?",
    "Should you live for today or plan for tomorrow?",
    "Is it better to have high expectations or low expectations?",
    "Does sharing your struggles show strength or weakness?",
    "Is perfection worth pursuing?",
    "Should loyalty require agreement?",
    "Is it more important to be interesting or to be interested?",
    "Can a lie ever be ethical?",
    "Should you trust people by default or make them earn it?",
    "Is conflict necessary for growth?",
    "Do actions speak louder than words?",
    "Should you finish what you start even if you've lost interest?",
    "Is independence more valuable than connection?",
    "Can you love someone and not trust them?",
    "Should you fix what's broken or start fresh?",
    "Is it better to be an optimist or a realist?",
    "Does being right matter more than being kind?",
    "Should you let go of the past or learn from it constantly?",
    "Is asking for help a sign of strength or weakness?",
    "Can you separate art from the artist?",
    "Should you be the same person in every situation?",
    "Is silence sometimes better than honesty?",
    "Do endings matter more than beginnings?",
    "Should principles be flexible or absolute?",
    "Is doubt a weakness or a form of wisdom?",
    "Can you be too open-minded?",
    "Should you defend your beliefs or stay curious?",
    "Is routine comforting or limiting?",
    "Does everyone deserve kindness?",
    "Should you trust your feelings or question them?",
    "Is originality overrated?",
    "Can you be both humble and confident?",
    "Should you show your emotions or maintain composure?",
    "Is closure necessary to move on?",
    "Do standards protect you or limit you?",
    "Should you speak your mind or consider the consequences first?",
    "Is being misunderstood inevitable?",
    "Can empathy be learned?",
    "Should you compromise your values for relationships?",
    "Is authenticity always appropriate?",
    "Do endings define the whole experience?",
    "Should work and personal life be separate?",
    "Is justice more important than mercy?",
    "Can you be content without being happy?",
    "Should you express gratitude publicly or privately?",
    "Is spontaneity more valuable than planning?",
    "Do we owe people explanations?",
    "Should you fight for what you want or accept what you have?",
    "Is change always growth?",
    "Can discipline and freedom coexist?",
    "Should you preserve traditions or embrace progress?",
    "Is waiting a sign of patience or indecision?",
    "Do we need contrast to appreciate happiness?",
    "Should you prioritize individual needs or collective good?",
    "Is certainty possible or just an illusion?",
    "Can you build character without struggle?",
    "Should you express yourself or protect your privacy?",
    "Is comparison inevitable?",
    "Do intentions justify actions?",
    "Should you chase excitement or cultivate peace?",
]

# ==================== SPARK — CHILL ====================

SPARK_CHILL = [
    "What's your comfort show that you can rewatch a million times?",
    "What's a small thing that always makes your day a little better?",
    "What's your go-to late-night snack?",
    "What's a song that instantly puts you in a good mood?",
    "What's the best meal you've had recently?",
    "What's something you're looking forward to this week?",
    "What's a hobby you've always wanted to try but haven't yet?",
    "What's your favorite thing about weekends?",
    "What's a movie you think everyone should watch at least once?",
    "What's the nicest compliment you've ever received?",
    "What's your favorite way to unwind after a long day?",
    "What's your current favorite song on repeat?",
    "What's a small win you've had recently?",
    "What's the last thing that made you genuinely laugh out loud?",
    "What's something you're grateful for today?",
    "What's a simple pleasure you enjoy every day?",
    "What's a book, movie, or show that changed your perspective on something?",
    "What's a random skill you wish you had?",
    "What's something you enjoy doing alone?",
    "What's your ideal lazy Sunday look like?",
    "What's a childhood memory that always makes you smile?",
    "What's the best advice someone gave you?",
    "What's a food you could never get tired of?",
    "What's your favorite thing about where you live?",
    "What's a video game you could play forever?",
    "What's a song lyric that's stuck with you?",
    "What's your favorite season and why?",
    "What's something new you learned recently?",
    "What's your go-to comfort food?",
    "What's a place you'd love to visit?",
    "What's your favorite way to spend a rainy day?",
    "What's a memory that still makes you laugh?",
    "What's something you're proud of but don't talk about much?",
    "What's your guilty pleasure TV show or movie?",
    "What's the most thoughtful gift you've ever received?",
    "What's a tradition you love?",
    "What's your favorite time of day?",
    "What's something that always calms you down?",
    "What's a compliment you gave someone recently?",
    "What's your favorite type of weather?",
    "What's a book that stuck with you long after you finished it?",
    "What's something you do that makes you feel like yourself?",
    "What's your favorite smell?",
    "What's a talent you have that most people don't know about?",
    "What's your favorite childhood game?",
    "What's something you'd like to be better at?",
    "What's your favorite way to celebrate small victories?",
    "What's a sound that instantly relaxes you?",
    "What's your favorite comfort outfit?",
    "What's something kind someone did for you recently?",
    "What's your favorite type of music to listen to when you're working?",
    "What's a place that feels like home to you?",
    "What's your favorite thing to cook or bake?",
    "What's something you're currently obsessed with?",
    "What's your favorite holiday and why?",
    "What's a quote that resonates with you?",
    "What's your favorite board game or card game?",
    "What's something you wish you could do every day?",
    "What's your favorite way to treat yourself?",
    "What's a random fact you find fascinating?",
    "What's your favorite thing about your best friend?",
    "What's a habit you're trying to build?",
    "What's your favorite piece of clothing you own?",
    "What's something that always cheers you up when you're down?",
    "What's your favorite thing about your morning routine?",
    "What's a skill you've developed that you're proud of?",
    "What's your favorite memory from this year so far?",
    "What's something you're looking forward to in the future?",
    "What's your favorite podcast or YouTube channel?",
    "What's a movie scene that always gets you emotional?",
    "What's your favorite way to spend time with friends?",
    "What's something you find beautiful?",
    "What's your favorite type of dessert?",
    "What's a goal you recently achieved?",
    "What's your favorite thing about your personality?",
    "What's something you wish more people knew about you?",
    "What's your favorite childhood book?",
    "What's something that makes you feel nostalgic?",
    "What's your favorite thing to do on a Friday night?",
    "What's a lesson you learned the hard way?",
    "What's your favorite way to stay active?",
    "What's something you're grateful for that you often take for granted?",
    "What's your favorite type of tea or coffee?",
    "What's a song that brings back good memories?",
    "What's your favorite thing about your hometown?",
    "What's something you're excited to learn more about?",
    "What's your favorite way to express creativity?",
    "What's a movie or show you can quote by heart?",
    "What's your favorite thing to do when you can't sleep?",
    "What's something that makes you feel peaceful?",
    "What's your favorite childhood TV show?",
    "What's a moment when you felt really proud of yourself?",
    "What's your favorite type of art?",
    "What's something you love about your daily routine?",
    "What's your favorite way to spend a Sunday morning?",
    "What's a compliment you've received that meant a lot?",
    "What's your favorite thing about autumn/fall?",
    "What's something you wish you could tell your younger self?",
    "What's your favorite thing about winter?",
    "What's a small thing you're really good at?",
    "What's your favorite thing about spring?",
    "What's something that always makes you smile?",
    "What's your favorite thing about summer?",
    "What's a hobby you'd recommend to others?",
    "What's your favorite way to stay connected with long-distance friends?",
    "What's something you're currently reading or watching?",
    "What's your favorite type of exercise or physical activity?",
    "What's a place where you feel most creative?",
    "What's your favorite way to help others?",
    "What's something you've accomplished recently that you're proud of?",
    "What's your favorite thing to do when you have free time?",
    "What's a movie soundtrack you love?",
    "What's your favorite thing about your current phase of life?",
    "What's something that makes you feel energized?",
    "What's your favorite childhood snack?",
    "What's a tradition you'd like to start?",
    "What's your favorite way to spend time outdoors?",
    "What's something you appreciate about yourself?",
    "What's your favorite midnight snack?",
    "What's a documentary you found really interesting?",
    "What's your favorite thing to do on a snow day?",
    "What's something you're passionate about?",
    "What's your favorite memory with your family?",
    "What's a small luxury that makes your life better?",
    "What's your favorite thing about where you work or study?",
    "What's something you learned from a mistake?",
    "What's your favorite way to practice self-care?",
    "What's a song you associate with a specific memory?",
    "What's your favorite thing about technology?",
    "What's something you wish you had more time for?",
    "What's your favorite inspirational quote or mantra?",
    "What's a cause you care deeply about?",
    "What's your favorite way to decompress after a stressful day?",
    "What's something you're curious about?",
    "What's your favorite thing about getting older?",
    "What's a random act of kindness you witnessed or experienced?",
    "What's your favorite form of entertainment?",
    "What's something that makes you feel at peace?",
]

# ==================== PERSONALITY QUESTIONS ====================

PERSONALITY_QUESTIONS = [
    "Would you rather tolerate ambiguity or demand clear answers?",
    "Would you rather lead a revolution or preserve what works?",
    "Would you rather be the most authentic version of yourself or the most successful version?",
    "Would you rather confront problems immediately or let them resolve naturally?",
    "Would you rather commit to one path or keep your options open?",
    "Would you rather be needed by many or deeply understood by few?",
    "Would you rather explore new ideas or perfect existing ones?",
    "Would you rather question everything or trust the process?",
    "Would you rather express yourself boldly or observe quietly?",
    "Would you rather make quick decisions or deliberate carefully?",
    "Would you rather adapt to people or have people adapt to you?",
    "Would you rather seek harmony or pursue truth?",
    "Would you rather be spontaneous or structured?",
    "Would you rather stand out or blend in?",
    "Would you rather focus on what's missing or appreciate what's present?",
    "Would you rather challenge the status quo or maintain stability?",
    "Would you rather be warm and approachable or mysterious and intriguing?",
    "Would you rather make others feel comfortable or intellectually stimulated?",
    "Would you rather prioritize your needs or others' needs?",
    "Would you rather live by principles or by circumstances?",
    "Would you rather be intensely passionate or calmly consistent?",
    "Would you rather speak directly or read between the lines?",
    "Would you rather value depth over breadth or breadth over depth?",
    "Would you rather initiate or respond?",
    "Would you rather seek novelty or find comfort in routine?",
    "Would you rather be independent or interdependent?",
    "Would you rather trust logic or trust intuition?",
    "Would you rather be certain and wrong or uncertain and learning?",
    "Would you rather influence culture or analyze it?",
    "Would you rather be transparent or strategic?",
    "Would you rather have inner peace or outer success?",
    "Would you rather be efficient or thorough?",
    "Would you rather simplify complexity or embrace it?",
    "Would you rather act on feelings or analyze them first?",
    "Would you rather be diplomatic or direct?",
    "Would you rather value consistency or growth?",
    "Would you rather honor tradition or create new paths?",
    "Would you rather have strong convictions or remain open-minded?",
    "Would you rather be seen as reliable or exciting?",
    "Would you rather focus on solutions or on understanding the problem?",
    "Would you rather be part of a community or be self-reliant?",
    "Would you rather be reserved until comfortable or open from the start?",
    "Would you rather be practical or idealistic?",
    "Would you rather maintain composure or show authentic emotion?",
    "Would you rather avoid conflict or address it head-on?",
    "Would you rather be systematic or flexible?",
    "Would you rather trust your first impression or gather more data?",
    "Would you rather value expertise or versatility?",
    "Would you rather commit fully or test the waters?",
    "Would you rather focus inward or outward?",
    "Would you rather seek closure or stay in possibility?",
    "Would you rather be content with simplicity or chase complexity?",
    "Would you rather value loyalty or honesty when they conflict?",
    "Would you rather lead by example or by instruction?",
    "Would you rather be motivated by fear or by inspiration?",
    "Would you rather have a few deep interests or many surface interests?",
    "Would you rather process internally or think out loud?",
    "Would you rather be accountable to yourself or to others?",
    "Would you rather work steadily or in bursts?",
    "Would you rather value originality or functionality?",
    "Would you rather be agreeable or authentic?",
    "Would you rather seek approval or seek truth?",
    "Would you rather be driven by duty or desire?",
    "Would you rather trust experience or experiment?",
    "Would you rather value being right or being effective?",
    "Would you rather be a specialist or a generalist?",
    "Would you rather have high standards for yourself or for others?",
    "Would you rather protect your energy or share it freely?",
    "Would you rather value impact or intent?",
    "Would you rather be persuasive or receptive?",
    "Would you rather have conviction or curiosity?",
    "Would you rather value competence or compassion?",
    "Would you rather be cautious or bold?",
    "Would you rather reflect before acting or act then reflect?",
    "Would you rather value what you think or how you feel?",
    "Would you rather finish strong or start strong?",
    "Would you rather embrace your strengths or work on your weaknesses?",
    "Would you rather be self-sufficient or ask for help?",
    "Would you rather value wisdom or knowledge?",
    "Would you rather be understood or respected?",
    "Would you rather trust the plan or trust your instincts?",
    "Would you rather have clarity or possibility?",
    "Would you rather value connection or autonomy?",
    "Would you rather be inspiring or grounding?",
    "Would you rather focus on what could go right or what could go wrong?",
    "Would you rather value impact or comfort?",
    "Would you rather be challenged or supported?",
    "Would you rather trust yourself or trust others?",
    "Would you rather be patient or urgent?",
    "Would you rather control your environment or adapt to it?",
    "Would you rather seek recognition or contentment?",
    "Would you rather be collaborative or autonomous?",
    "Would you rather value consistency or flexibility?",
    "Would you rather be memorable or reliable?",
    "Would you rather embrace risk or minimize it?",
    "Would you rather value being unique or being relatable?",
    "Would you rather seek mastery or discovery?",
    "Would you rather value freedom or security?",
    "Would you rather be complex or straightforward?",
    "Would you rather be provocative or diplomatic?",
    "Would you rather value inner truth or external validation?",
    "Would you rather be proactive or reactive?",
    "Would you rather value tradition or innovation?",
    "Would you rather seek patterns or exceptions?",
    "Would you rather be organized or spontaneous?",
    "Would you rather value being prepared or being present?",
    "Would you rather be selective or inclusive?",
    "Would you rather value achievement or peace?",
    "Would you rather be intense or easygoing?",
    "Would you rather trust process or trust outcomes?",
    "Would you rather be a starter or a finisher?",
    "Would you rather value depth of thought or speed of thought?",
    "Would you rather be focused or multitasking?",
    "Would you rather value privacy or openness?",
    "Would you rather be goal-oriented or present-focused?",
    "Would you rather trust data or trust gut feelings?",
    "Would you rather value precision or approximation?",
    "Would you rather be self-critical or self-accepting?",
    "Would you rather embrace change or create stability?",
    "Would you rather value meaning or pleasure?",
    "Would you rather be rational or emotional in crisis?",
    "Would you rather value justice or mercy?",
    "Would you rather seek control or seek flow?",
    "Would you rather be questioned or trusted?",
    "Would you rather value contribution or independence?",
    "Would you rather be seen or heard?",
    "Would you rather value being right or being kind?",
    "Would you rather seek perfection or progress?",
    "Would you rather value your past or your future?",
    "Would you rather be optimistic or realistic?",
    "Would you rather value experiences or achievements?",
    "Would you rather be assertive or receptive?",
    "Would you rather value solitude or companionship?",
    "Would you rather be a dreamer or a doer?",
    "Would you rather value quality or quantity?",
    "Would you rather be misunderstood doing what's right or understood doing what's wrong?",
    "Would you rather value being interesting or being kind?",
    "Would you rather seek truth or seek peace?",
    "Would you rather be intellectually consistent or emotionally authentic?",
    "Would you rather value certainty or possibility?",
    "Would you rather be comfortable being disliked or uncomfortable being liked?",
    "Would you rather value being heard or being seen?",
    "Would you rather trust your values or trust your reasoning?",
    "Would you rather value internal validation or external impact?",
    "Would you rather be warm and vague or cold and clear?",
    "Would you rather value being understood deeply by few or liked generally by many?",
    "Would you rather seek what's meaningful or what's enjoyable?",
    "Would you rather value exploration or mastery?",
    "Would you rather be principled or pragmatic?",
    "Would you rather value depth in relationships or breadth in connections?",
    "Would you rather be introspective or action-oriented?",
    "Would you rather value self-awareness or confidence?",
    "Would you rather be someone people admire or someone people trust?",
    "Would you rather value being capable or being connected?",
    "Would you rather seek novelty or refine familiarity?",
    "Would you rather value being genuine or being tactful?",
    "Would you rather trust your analysis or trust your experience?",
    "Would you rather be independent in thought or aligned in action?",
    "Would you rather value individual expression or collective harmony?",
    "Would you rather be someone who questions or someone who believes?",
    "Would you rather value what you build or who you become?",
    "Would you rather be respected for intelligence or loved for warmth?",
    "Would you rather value radical honesty or thoughtful discretion?",
    "Would you rather be someone who initiates change or someone who supports it?",
    "Would you rather value self-discipline or self-compassion?",
    "Would you rather be intellectually rigorous or emotionally present?",
    "Would you rather value being consistent or being adaptive?",
    "Would you rather be someone who protects or someone who empowers?",
    "Would you rather value efficiency or meaningfulness?",
    "Would you rather trust the journey or focus on the destination?",
    "Would you rather be valued for what you do or who you are?",
    "Would you rather value being rational or being compassionate?",
    "Would you rather be a person of few words or many?",
    "Would you rather value independence of mind or connection of heart?",
    "Would you rather be someone who stands firm or someone who bends?",
    "Would you rather value being logical or being understanding?",
    "Would you rather be a guardian of values or an explorer of ideas?",
    "Would you rather value thinking deeply or feeling deeply?",
    "Would you rather be someone who challenges or someone who accepts?",
    "Would you rather value your reputation or your integrity?",
    "Would you rather be privately fulfilled or publicly successful?",
    "Would you rather value what you know or what you discover?",
    "Would you rather be someone who converges or someone who diverges?",
    "Would you rather value order or freedom?",
    "Would you rather be motivated by ideals or by reality?",
    "Would you rather value substance over style or style over substance?",
    "Would you rather be someone who holds space or someone who fills it?",
    "Would you rather value coherence or creativity?",
    "Would you rather be guided by principles or by circumstances?",
    "Would you rather value being grounded or being visionary?",
    "Would you rather be someone who preserves or someone who transforms?",
    "Would you rather value commitment or exploration?",
    "Would you rather be someone other people lean on or someone who leans on themselves?",
]
