"""
Bot Configuration — All settings, messages, and question banks.
Edit this file to customize the bot's behavior and content.
"""

# ==================== SETTINGS ====================

TIMEZONE = "Asia/Manila"

# Chatter reward time (Manila time). Daily questions use auto-rotation (24h / question count).
CHATTER_SCHEDULE = {"hour": 23, "minute": 59}

CHIPS = {
    "name": "chips",
    "emoji": "🥔",
    "singular": "chip",
    "plural": "chips",
    "rewards": {
        "top_chatter": 10000,
        "second_chatter": 5000,
        "third_chatter": 3000,
        "chip_drop": 10,
    },
}

CHIP_DROP = {
    "activity_window": 10,      # minutes - check for recent activity before scheduling
    "min_delay": 1,             # minutes - minimum delay before drop after activity detected
    "max_delay": 60,            # minutes - maximum delay before drop
    "min_cooldown_hours": 1,    # hours - minimum cooldown after grab
    "max_cooldown_hours": 10,   # hours - maximum cooldown after grab
    "min_amount": 1000,         # minimum chips per drop
    "max_amount": 10000,        # maximum chips per drop
    "math_chance": 0.50,        # 50% chance for math question
    "timeout": 900,             # seconds before drop expires (15 min)
}

ACTIVITY_REWARDS = {
    "hour": 23,
    "minute": 59,
    "first_place": 3000,
    "second_place": 2000,
    "third_place": 1000,
}

CODE_PURPLE = {
    "inactivity_hours": 7,
    "cooldown_hours": 24,
}

FEATURES = {
    "warm": True,
    "chill": True,
    "typology": True,
    "chatter_rewards": True,
    "chip_drops": True,
    "code_purple": True,
    "activity_rewards": True,
}

LEADERBOARD = {
    "page_size": 10,
}

# ==================== EMBED CONFIG ====================

AUTHOR_NAME = ""

# Colors as hex WITHOUT the # prefix (used with int(x, 16))
COLORS = {
    "warm": "FF6B6B",
    "chill": "4ECDC4",
    "typology": "FFD700",
    "leaderboard": "FF8C00",
}

EMBEDS = {
    "warm": {
        "title": "🔥 Warm Question",
    },
    "chill": {
        "title": "🌙 Chill Question",
    },
    "typology": {
        "title": "✨ Typology Question",
    },
    "leaderboard": {
        "title": "🏆 Chip Leaderboard",
        "footer": "Use /balance to check yours",
        "rank_emojis": {"1": "🥇", "2": "🥈", "3": "🥉", "default": "🔹"},
    },
}

# ==================== MESSAGES ====================

MESSAGES = {
    "chip_drop": {
        "grab_announcement": "**RANDOM CHIP DROP EVENT:**\nFirst person to type `~grab` wins **+{amount} {emoji}** chips!",
        "math_announcement": "**RANDOM CHIP DROP EVENT:**\nFirst person to answer `{equation}` wins **+{amount} {emoji}** chips!",
        "claimed": [
            "**{user}** was first to snatch **+{amount} {emoji}**!",
            "Nice! **{user}** just grabbed **+{amount} {emoji}**!",
            "**{user}** swooped in and claimed **+{amount} {emoji}**!",
        ],
        "expired": [
            "...Nobody claimed them. They're gone now",
            "Chips expired. Maybe next time...",
            "Too late, they're gone",
            "And... nobody grabbed them. Rip chips :(",
        ],
    },
    "activity_rewards": {
        "announcement": "**Daily Activity Rewards 🏆**",
        "first_place": "🥇 **{user}** — **+{amount} {emoji}** ({points} points)",
        "second_place": "🥈 **{user}** — **+{amount} {emoji}** ({points} points)",
        "third_place": "🥉 **{user}** — **+{amount} {emoji}** ({points} points)",
        "no_activity": "No activity today. No rewards.",
    },
    "code_purple": [
        "Code purple...",
        "...code purple?",
        "helloooo? anyone there? code purple guysss...",
        "Ehem...... **taps mic** code purple.",
        "Somebody say something in the server challenge (IMPOSSIBLE!!) (NOT CLICKBAIT!)",
        "The silence is deafening... code purple",
        "...y'all alive? code purple...",
        "# Code Purple.",
        "no one has chatted in a while... code purple :(",
        "anyone there? code purple",
        "I'm just a bot no one appreciates :(",
        "-# code purple... anyone? :(",
    ],
    "chatter_reward": {
        "announcement": "**Daily Chatter Rewards 💬**",
        "top_chatter": "🥇 **{user}** — **+{amount} {emoji}**",
        "second_chatter": "🥈 **{user}** — **+{amount} {emoji}**",
        "third_chatter": "🥉 **{user}** — **+{amount} {emoji}**",
        "no_activity": "Nobody chatted today. No rewards.",
    },
    "balance": {
        "response": "You have **{amount} {emoji}** (ranked **{rank}**)",
        "no_balance": "You don't have any chips yet. Chat more 🥔",
        "unranked": "Unranked",
    },
    "leaderboard": {
        "entry": "{emoji} **{rank}.** {user} — **{amount} {currency}**",
        "your_position": "Your position: **#{rank}** with **{amount} {currency}**",
        "empty": "Well... Nobody has chips yet.",
    },
    "errors": {
        "generic": "Something went wrong. Try again later.",
    },
    "success": {
        "force_drop": "Chip drop triggered.",
    },
    "word_game": {
        "started": "🎮 Word game started! Just type a word to add it to the story.",
        "ended": "📖 {user} ended the story! ({count} words total).",
        "word_added": "✓ Added \"{word}\".",
        "already_active": "A word game is already in progress! Use `/wordgame end` to finish it first.",
        "no_game": "No active word game! Start one with `/wordgame start`.",
        "no_game_end": "No active word game to end.",
        "wrong_channel": "Word game is only active in <#{channel}>.",
        "failed": "Failed to start game - check bot permissions.",
        "not_a_word": "That's not a word! Only single words allowed.",
        "not_a_word_snarky": "That's not a word! ...you *do* know how the game works right?",
        "consecutive": "You can't add two words in a row! Let someone else go.",
    },
}

WORD_GAME = {
    "embed": {
        "title": "📖 Word Game",
        "title_ended": "📖 Story Complete!",
        "empty_story": "*Type a word to start the story!*",
        "footer": "Create a collaborative story, one word at a time!",
        "footer_ended": "words total",
        "last_word_by": "Last word by",
        "color": "9B59B6",
    },
}

# ==================== TYPOLOGY ====================

MBTI_TYPES = [
    "INTJ", "INTP", "ENTJ", "ENTP",
    "INFJ", "INFP", "ENFJ", "ENFP",
    "ISTJ", "ISFJ", "ESTJ", "ESFJ",
    "ISTP", "ISFP", "ESTP", "ESFP",
]

ENNEAGRAM_TYPES = [
    "1w9", "1w2", "2w1", "2w3", "3w2", "3w4",
    "4w3", "4w5", "5w4", "5w6", "6w5", "6w7",
    "7w6", "7w8", "8w7", "8w9", "9w8", "9w1",
]

TYPOLOGY_QUESTIONS = [
    "Who would you prefer as your teacher?",
    "Who would you rather hang out with for an entire day?",
    "Who would you trust more to handle conflict in a group setting?",
    "Who would you trust more with a secret?",
    "Who would you rather party with?",
    "Who do you think would win in a debate?",
    "Who would you prefer as your project leader?",
    "Who would you rather go on a road trip with?",
    "Who do you think is more likely to start a business?",
    "Who would you rather go to for life advice?",
    "Who would you rather have as a roommate?",
    "Who do you think would win in a trivia competition?",
    "Who would you trust more to handle stress during a crisis?",
    "Who do you think is more likely to make you laugh?",
    "Who would you trust to plan your birthday party?",
    "Who would you prefer as your therapist?",
    "Who would you rather work on a group project with?",
    "Who do you think would win in a chess match?",
    "Who would you rather travel with internationally?",
    "Who do you think would handle a breakup more gracefully?",
    "Who would you want on your trivia team?",
    "Who would you trust more to negotiate a raise?",
    "Who do you think would win in a cooking competition?",
    "Who would you prefer as your loyal friend?",
    "Who would you rather have as your mentor?",
    "Who would you trust more in awkward social situations?",
    "Who would you prefer for a long-distance friendship?",
    "Who would you trust to give honest feedback?",
    "Who do you think would win at a creative challenge?",
    "Who would you prefer as your creative partner?",
    "Who do you think is more likely to remember your birthday?",
    "Who would you rather debate with?",
    "Who would you prefer to comfort you when sad?",
    "Who do you think would handle rejection more gracefully?",
    "Who would you prefer as your podcast co-host?",
    "Who do you think would win in a physical challenge?",
    "Who would you rather share an apartment with?",
    "Who would you trust more to keep you motivated?",
    "Who would you rather have a prank war with?",
    "Who would you trust to help you move?",
    "Who do you think would win at solving a mystery?",
    "Who would you rather choose as study partners?",
    "Who do you think is more likely to defend you in an argument?",
    "Who would you rather have plan your wedding?",
    "Who would you prefer as your dinner party host?",
    "Who do you think would handle long work hours better?",
    "Who would you trust more with your pet?",
    "Who do you think would win in a survival situation?",
    "Who would you rather have as your backpacking travel companion?",
    "Who would you prefer for support during tough times?",
    "Who do you think would handle sudden change better?",
    "Who would you rather collaborate with on creative work?",
    "Who would you prefer to cheer you up?",
    "Who would you rather have a conversation with?",
    "Who do you think would handle public speaking better?",
    "Who do you think would win at video games?",
    "Who would you rather receive criticism from?",
    "Who would you prefer to organize an event?",
    "Who would you prefer as your emergency contact?",
]

# ==================== PERSONAL TYPOLOGY QUESTIONS ====================

PERSONAL_TYPOLOGY_QUESTIONS = [
    "What cognitive function do you wish you had more access to?",
    "If you could swap types with someone for a day, which type would you choose?",
    "What's a typology stereotype about your type that you actually fit?",
    "What's a typology stereotype about your type that annoys you the most?",
    "Which cognitive function do you think is most overrated?",
    "Which cognitive function do you think is most underrated?",
    "What's the biggest misconception people have about your type?",
    "If you were forced to be a different MBTI type, which would you pick?",
    "What enneagram type do you find most misunderstood?",
    "What's a trait from your shadow functions that sometimes shows up?",
    "Which type do you think you'd clash with most and why?",
    "What's the hardest part about being your type?",
    "What's the best part about being your type?",
    "Which type do you secretly admire but would never want to be?",
    "What cognitive function do you catch yourself overusing?",
    "What's a 'growth edge' for your type that you struggle with?",
    "Which type do you think gets stereotyped most unfairly?",
    "What's a function pair you wish you had instead of your own?",
    "If your inferior function was suddenly your dominant, how would your life change?",
    "What type do you think you acted like as a child?",
    "What enneagram type do you think you'd be if raised differently?",
    "Which typology system do you find most accurate for you — MBTI, enneagram, AP, or something else?",
    "What's a cognitive function you used to think you had but realized you don't?",
    "What's the most 'un-[your type]' thing about you?",
    "Which type do you find easiest to communicate with?",
    "Which type do you find hardest to understand?",
    "What's a question you're tired of people asking about your type?",
    "What's a function stack you find fascinating but don't fully get?",
    "If cognitive functions had flavors, what would yours taste like?",
    "What type do you mistype as most often and why?",
    "What's an enneagram wing combination you find interesting?",
    "How does your instinctual stacking show up differently at home vs in public?",
    "How does your instinctual stacking affect your daily life?",
    "What's the biggest difference between sp-first and sx-first versions of your enneagram type?",
    "If you could change your dominant instinct for a week, which would you choose?",
    "What's a stereotype about your instinctual variant that's actually true for you?",
    "Which instinctual variant do you find most attractive in others?",
    "How do you think your blind instinct affects your relationships?",
    "What's a behavior that screams 'sx-dom' to you?",
    "What's a behavior that screams 'sp-dom' to you?",
    "What's a behavior that screams 'so-dom' to you?",
    "Do you think your instinctual variant or enneagram type affects you more day-to-day?",
    "What instinctual variant do you think is most misunderstood?",
    "How would you describe the difference between so3 and sx3?",
    "Which instinct do you think is hardest to develop as a blind spot?",
    "What's a hot take you have about instinctual variants?",
    "Do you relate more to your instinctual stacking or your tritype?",
    "What enneagram + instinctual combo do you find most fascinating?",
    "How does your second instinct show up compared to your dominant one?",
    "What type do you think you'd become under extreme stress?",
    "What type do you think has the hardest time in modern society?",
    "What's a type pairing that you think is overrated?",
    "What's a type pairing you think is underrated?",
    "Which cognitive function do you find most attractive in others?",
    "What's a trait coded as your type that you genuinely don't have?",
    "If you could master one cognitive function overnight, which would it be?",
    "What type do you think ages the best?",
    "What's your hottest typology take?",
    "What enneagram core fear do you relate to even if it's not your type?",
    "What's a typology meme about your type that's actually accurate?",
    "Which type do you think gives the best advice?",
    "Which type do you think gives the worst advice?",
    "What's a trait from your tertiary function that you've developed?",
    "If your dominant and auxiliary functions swapped, what would change?",
    "What's a type combo (MBTI + enneagram) you find intriguing?",
    "What cognitive function do you wish your friends had more of?",
    "What's the most annoying thing about being typed?",
    "Which type do you think handles failure best?",
    "Which type do you think handles success best?",
    "What's something about your type that tests don't capture?",
    "What's a typing you disagree with (celebrities, characters, etc.)?",
    "If you had to pick a tritype, what would it be and why?",
    "What's a cognitive function that feels completely foreign to you?",
    "What's your unpopular opinion about the MBTI community?",
    "What type do you think you'd parent best or worst?",
    "What's a function loop you've caught yourself in?",
    "Which type do you think is most likely to mistype themselves?",
    "What's a strength of your inferior function you've noticed?",
    "What type do you think the world needs more of right now?",
    "What's a typing rabbit hole you went down recently?",
    "What's the best description of your type you've ever read?",
    "Which enneagram integration/disintegration line resonates most with you?",
    "What would you tell someone who just discovered they're your type?",
    "What's a type you find yourself consistently drawn to as friends?",
    "What's a type you've dated that surprised you?",
    "If your cognitive stack was a team, who would be the MVP?",
    "What type do you think makes the best creative partner?",
    "What type do you think makes the best work partner?",
    "What's a cognitive function you used to hate but now appreciate?",
    "What's something your type tends to avoid but you don't?",
    "Which type do you think has the most accurate self-image?",
    "Which type do you think has the least accurate self-image?",
    "What's a type-related question you wish more people asked?",
    "What function do you think is hardest to develop later in life?",
    "If you could give your younger self a 'type manual,' what would it say?",
    "What type do you think you'd be in a parallel universe?",
    "What's the weirdest way you've related to your type description?",
    "What function do you think you use most in conflict?",
    "What type do you think handles conflict worst?",
    "What's a type you used to dismiss but now respect?",
    "If your functions were coworkers, how would they interact?",
    "What's a type you've met IRL that changed your view of them?",
    "What enneagram type do you find hardest to read?",
    "What's a cognitive function you wish was more talked about?",
    "What type combo would you love to see a deep dive video on?",
    "What function do you rely on too much in decision-making?",
    "What type do you think is most self-aware?",
    "What type do you think is least self-aware?",
    "What's a typing system you think is underrated?",
    "What's a typing system you think is overrated?",
    "If you woke up as your opposite type, what would be hardest?",
    "What's a shadow function you've caught yourself using?",
    "Which type do you think experiences the most internal conflict?",
    "What's a function pair you find harmonious in others?",
    "What cognitive function do you think gets misidentified most often?",
    "What's a take about your type that made you feel seen?",
    "What type do you think tells the best stories?",
    "What's a type you underestimated until you got to know one?",
    "What's the most 'typical' thing you do for your type?",
    "What cognitive function makes you the most uncomfortable?",
    "What's a personality pattern you've noticed in your family?",
    "What's a function you've seen in action that impressed you?",
    "What type do you think has the most unique sense of humor?",
    "What's a blind spot you've noticed in your own function stack?",
    "If you could ask any type one question, what would it be?",
    "What enneagram motivation do you relate to that isn't yours?",
    "What type do you think is most likely to overthink their type?",
    "What's a typing you've had to defend to others?",
    "What function do you think is most misunderstood overall?",
    "What type would you trust with your most vulnerable moment?",
    "What's a typology habit you have that others find weird?",
    "What function shows up most in your hobbies?",
    "What's a type community online that you enjoy or avoid?",
    "What type do you think has the strongest gut instincts?",
    "What's a value your type shares that you don't personally hold?",
    "What's a trait that's 'off-brand' for your type that you embrace?",
    "What's the funniest mistyping you've ever witnessed?",
    "What cognitive function would you want more of in society?",
    "What type do you think processes emotions the fastest?",
    "What function do you think is overrepresented in media?",
    "What type do you think is most likely to research typology deeply?",
    "What's a function you've seen develop in someone over time?",
    "What would your type's theme song be?",
    "What type do you wish had more representation in fiction?",
    "What cognitive function do you express most in relationships?",
    "What's the most surprising thing about your enneagram type?",
    "What type do you find intimidating and why?",
    "What's a typing you had to sit with before accepting?",
    "What function do you think modern life suppresses most?",
    "What type do you think handles uncertainty the best?",
    "What type do you think handles uncertainty the worst?",
    "What's a cognitive process you catch yourself explaining to others?",
    "What's the most healing thing about knowing your type?",
    "What's a type you relate to in unexpected ways?",
    "What function would you want to 'borrow' from another type?",
    "What type do you think asks the best questions?",
    "What function do you think is crucial for emotional intelligence?",
    "If your type had a mascot, what would it be?",
    "What's a typology concept you think gets overcomplicated?",
    "What's a limit of typology that you've personally experienced?",
    "What type do you think lives most authentically?",
    "What's something that only people of your type would understand?",
    "What cognitive function do you think is most important in leadership?",
    "What type do you think would survive best in a zombie apocalypse?",
    "What enneagram growth line have you experienced?",
    "What function do you notice most in strangers?",
    "What's the biggest gift your type has to offer the world?",
    "What do sp-blinds struggle with that sp-doms take for granted?",
    "What do sx-blinds struggle with that sx-doms take for granted?",
    "What do so-blinds struggle with that so-doms take for granted?",
    "How does your instinctual variant affect how you experience your enneagram core fear?",
    "What's an instinct combo (like sp/sx or so/sp) that you find intriguing?",
    "Would you rather have sx-blind or so-blind as your stacking?",
    "What's something you wish people understood about your typology?",
    "What type you think is most likely to have a type-related existential crisis?",
    "What's something you wish you could tell your past self before learning about typology?",
    "Would a world where everyone knew about typology be better or worse, in your opinion, and why?",
    "Do you think knowing your type changed you for better or worse?",
    "What's the most surprising thing you learned about yourself through typology?",
    "Do you think typology makes it easier or harder to connect with people?",
    "What's something about typology that you think is overemphasized?",
    "What's something about typology that you think is underemphasized?",
    "How do you explain typology to people who've never heard of it?",
    "Do you think typology is more useful for understanding yourself or others?",
    "What's a common typology debate you're tired of seeing?",
    "Do you think being mistyped for a long time affected you?",
    "What made you first get into typology?",
    "Do you wish you discovered typology earlier or later in life?",
    "What's the weirdest typology take you've ever heard?",
    "Do you think typology helps or hurts self-improvement?",
    "What's your relationship with typology like now vs when you first discovered it?",
    "Do you think typology can predict compatibility in relationships?",
    "What's a typology opinion you used to have but completely changed?",
    "Do you think some types are naturally better at typology than others?",
    "What's the most useful thing typology has taught you?",
    "What's the most useless thing about typology in your opinion?",
    "Do you think typology makes you more judgmental or more understanding?",
    "What's something you believed about typology that turned out to be wrong?",
    "Do you think typology has a toxicity problem?",
    "What's the biggest misconception non-typers have about typology?",
    "Do you think typology should be kept niche or become mainstream?",
    "What would you change about the typology community if you could?",
    "Do you think typology is more science or pseudoscience?",
    "What's a question you have about typology that no one seems to answer?",
    "Do you think typology helps with mental health or complicates it?",
    "What's your unpopular opinion about the enneagram community?",
    "Do you think you'll still be into typology 5 years from now?",
    "What's the most relatable typology content you've ever seen?",
    "What's the most cringe typology content you've ever seen?",
    "Do you think some typing systems work better for certain people?",
    "What's a typology resource everyone should check out?",
    "Do you think knowing someone's type before meeting them helps or hurts?",
    "What's something typology helped you forgive yourself for?",
    "Do you think typology excuses bad behavior or explains it?",
    "What's a part of typology you still don't fully understand?",
    "Do you prefer learning about typology through videos, articles, or discussions?",
    "What's the first thing you notice when trying to type someone?",
    "Do you think you're good at typing people or do you second-guess yourself?",
    "What's a typing you were confident about but turned out wrong?",
    "Do you think typology works better for typing yourself or others?",
    "What's something you wish typology content creators talked about more?",
    "Do you think typology has made you more or less patient with people?",
    "What's a typology phrase or term you're tired of hearing?",
]

# ==================== FRIEND GROUP QUESTIONS ====================

FRIEND_GROUP_QUESTIONS = [
    "Who here is most likely to become famous for something weird?",
    "Who here is most likely to survive a zombie apocalypse?",
    "Who here is most likely to accidentally start a cult?",
    "Who here is most likely to win an argument they're wrong about?",
    "Who here is most likely to get away with a crime?",
    "Who here is most likely to become a villain in their origin story?",
    "Who here is most likely to fake their own death for fun?",
    "Who here is most likely to get canceled on Twitter?",
    "Who here is most likely to randomly disappear and come back with snacks?",
    "Who here is most likely to cry because someone else is crying?",
    "Who here is most likely to adopt a stray cat?",
    "Who here is most likely to have a secret nobody knows?",
    "Who here is most likely to overthrow a government?",
    "Who here is most likely to get kidnapped and befriend the kidnapper?",
    "Who here is most likely to cause an international incident?",
    "Who here is most likely to get overly invested in a random mobile game?",
    "Who here is most likely to know random trivia about everything?",
    "Who here is most likely to go viral for the wrong reasons?",
    "Who here is most likely to accidentally binge watch a whole series without realizing it?",
    "Who here is most likely to befriend someone they just met in line?",
    "Who here is most likely to have a weirdly specific skill nobody expects?",
    "Who here is most likely to become a supervillain?",
    "Who here is most likely to fake being sick to skip something?",
    "Who here is most likely to lie on their resume?",
    "Who here is most likely to overthink a text for an hour?",
    "Who here is most likely to drop everything for someone they just met?",
    "Who here is most likely to have a villain arc?",
    "Who here is most likely to manipulate someone without realizing?",
    "Who here is most likely to start a revolution?",
    "Who here is most likely to become a conspiracy theorist?",
    "Who here is most likely to get caught up in drama they didn't start?",
    "Who here is most likely to ruin a surprise party?",
    "Who here is most likely to get lost in their own neighborhood?",
    "Who here is most likely to bring a knife to a gunfight and win?",
    "Who here is most likely to die first in a horror movie?",
    "Who here is most likely to survive purely out of spite?",
    "Who here is most likely to fake an accent for no reason?",
    "Who here is most likely to still sleep with a stuffed animal?",
    "Who here is most likely to run away and join the circus?",
    "Who here is most likely to become a TikTok influencer?",
    "Who here is most likely to ghost someone they've known for years?",
    "Who here is most likely to write an exposé about this friend group?",
    "Who here is most likely to sell out for brand deals?",
    "Who here is most likely to marry rich?",
    "Who here is most likely to become a hermit?",
    "Who here is most likely to fake their way into a career?",
    "Who here is most likely to start beef with a celebrity?",
    "Who here is most likely to become internet famous overnight?",
    "Who here is most likely to go off the grid?",
    "Who here is most likely to accidentally commit a felony?",
    "Who here is most likely to cry at a Pixar movie?",
    "Who here is most likely to get banned from a public place?",
    "Who here is most likely to start a fight over nothing?",
    "Who here is most likely to become a cryptobro?",
    "Who here is most likely to join a commune?",
    "Who here is most likely to have main character syndrome?",
    "Who here is most likely to fake being rich?",
    "Who here is most likely to become a standup comedian?",
    "Who here is most likely to have the most unhinged search history?",
    "Who here is most likely to send memes at 3am?",
    "Who here is most likely to name their plants and apologize when they die?",
    "Who here is most likely to argue with a wall and lose?",
    "Who here is most likely to start a podcast nobody listens to?",
    "Who here is most likely to become a professional gambler?",
    "Who here is most likely to get arrested for something stupid?",
    "Who here is most likely to become a cult member?",
    "Who here is most likely to fake an injury for attention?",
    "Who here is most likely to start a YouTube channel and give up in a week?",
    "Who here is most likely to talk to animals like they understand?",
    "Who here is most likely to have an emotional support playlist for every mood?",
    "Who here is most likely to get famous and forget about everyone?",
    "Who here is most likely to go viral for something embarrassing?",
    "Who here is most likely to become a politician?",
    "Who here is most likely to trip over nothing?",
    "Who here is most likely to remember everyone's birthday without reminders?",
    "Who here is most likely to get emotionally attached to fictional characters?",
    "Who here is most likely to organize their books by color instead of genre?",
    "Who here is most likely to make up elaborate backstories for strangers they see?",
    "Who here is most likely to get exposed in a documentary?",
    "Who here is most likely to have a burner account?",
    "Who here is most likely to fake their death on social media?",
    "Who here is most likely to become a true crime podcast host?",
    "Who here is most likely to accidentally become a meme?",
    "Who here is most likely to get doxxed?",
    "Who here is most likely to start drama in the group chat?",
    "Who here is most likely to rage quit something important?",
    "Who here is most likely to become an influencer's worst nightmare?",
    "Who here is most likely to get into a Twitter fight with their employer?",
    "Who here is most likely to impulse buy something ridiculous?",
    "Who here is most likely to become a motivational speaker?",
    "Who here is most likely to get kicked out of a Discord server?",
    "Who here is most likely to troll someone too hard?",
    "Who here is most likely to delete their account after one bad take?",
    "Who here is most likely to become internet infamous?",
    "Who here is most likely to accidentally reveal a secret?",
    "Who here is most likely to start a rumor?",
    "Who here is most likely to win a reality TV show?",
    "Who here is most likely to get in trouble for arguing online?",
    "Who here is most likely to be the subject of a true crime documentary?",
    "Who here is most likely to fake cry to get out of trouble?",
]

# ==================== SPARK WOULD YOU RATHER (WYR) ====================

SPARK_WYR = [
    # Social Cost Dilemmas
    "Would you rather everyone forget you exist for a month or remember every embarrassing thing you've done?",
    "Would you rather never be able to apologize or never be able to forgive?",
    "Would you rather have to say everything you think out loud or never speak your mind?",
    "Would you rather be the one who always texts first or never get texts from anyone?",
    "Would you rather everyone read your DMs or your search history?",
    "Would you rather always be overdressed or always be underdressed?",
    "Would you rather people think you're boring or think you're too much?",
    "Would you rather be loved but not respected or respected but not loved?",
    "Would you rather have no privacy but loyal friends or total privacy but no close relationships?",
    "Would you rather be known for something embarrassing or not be known at all?",
    
    # Career & Money Tradeoffs
    "Would you rather make a lot of money doing something boring or little money doing what you love?",
    "Would you rather be your own broke boss or rich working for someone you hate?",
    "Would you rather work 80 hours a week making bank or 20 hours barely getting by?",
    "Would you rather get a job through nepotism or struggle to get one on merit?",
    "Would you rather have your dream job but never have work-life balance or hate your job but have all the free time?",
    "Would you rather be wildly successful at 50 or moderately successful now?",
    "Would you rather get promoted but everyone hates you or stay where you are but be liked?",
    "Would you rather retire early but poor or retire late but comfortable?",
    "Would you rather start a business that might fail or keep a stable job you hate?",
    "Would you rather work remote forever but lonely or in office with people but commuting?",
    
    # Relationship Sacrifices
    "Would you rather date someone you love who doesn't love you back or someone who loves you but you don't love?",
    "Would you rather be in a relationship with no chemistry or no emotional connection?",
    "Would you rather your partner be attractive but dumb or ugly but brilliant?",
    "Would you rather never fall in love again or fall in love but get heartbroken every time?",
    "Would you rather be with someone perfect for you but your family hates or someone your family loves but isn't right for you?",
    "Would you rather stay single forever or settle for someone mediocre?",
    "Would you rather know your partner is cheating or never find out?",
    "Would you rather date someone clingy or emotionally unavailable?",
    "Would you rather be with someone who's always right or always thinks they're right?",
    "Would you rather have a partner who's your best friend but no spark or passionate but toxic?",
    
    # Friend Group Dynamics
    "Would you rather have 100 fake friends or 1 real one?",
    "Would you rather be the least liked in a popular group or most liked in an unpopular group?",
    "Would you rather call out your friend and ruin the friendship or stay silent and resent them?",
    "Would you rather your friend group roast you or ignore you?",
    "Would you rather have friends who are fun but unreliable or boring but always there?",
    "Would you rather be the therapist friend or the comic relief?",
    "Would you rather have a friend who overshares or one who never shares anything?",
    "Would you rather lose a toxic friend or keep them to avoid drama?",
    "Would you rather be in a friend group where you're always left out of inside jokes or be the joke?",
    "Would you rather have friends who challenge you or friends who always agree?",
    
    # Personal Identity Tradeoffs
    "Would you rather be yourself and lonely or fake and popular?",
    "Would you rather hide your interests to fit in or be authentic and judged?",
    "Would you rather change everything about yourself and be happy or stay the same and miserable?",
    "Would you rather be known for your looks or your personality?",
    "Would you rather have everyone know your secrets or live a lie forever?",
    "Would you rather be average at everything or excellent at one thing but terrible at the rest?",
    "Would you rather have a boring life with no regrets or an exciting life full of mistakes?",
    "Would you rather be attractive but insecure or average but confident?",
    "Would you rather be book smart but socially awkward or street smart but academically behind?",
    "Would you rather be funny but never taken seriously or serious but boring?",
    
    # Communication Dilemmas
    "Would you rather never be able to text or only be able to communicate through text?",
    "Would you rather be left on read forever or get a harsh response?",
    "Would you rather always have to sugarcoat or always be brutally honest?",
    "Would you rather overshare everything or never open up?",
    "Would you rather argue every day or never voice disagreements?",
    "Would you rather give advice no one takes or never be asked for advice?",
    "Would you rather apologize for everything or never apologize?",
    "Would you rather people always misunderstand you or you always misunderstand them?",
    "Would you rather know what people say about you behind your back or never know?",
    "Would you rather be the person who ghosts or gets ghosted?",
    
    # Life Path Choices
    "Would you rather live in your hometown forever or move somewhere new but miss home?",
    "Would you rather pursue your dream and fail or not try and always wonder?",
    "Would you rather have a normal life with no drama or an exciting life with constant chaos?",
    "Would you rather go back and fix your past or see your future?",
    "Would you rather live fast and die young or live long but boring?",
    "Would you rather take the safe route and regret it or risk it all and fail?",
    "Would you rather be stuck in the past or anxious about the future?",
    "Would you rather have your life planned out or completely unpredictable?",
    "Would you rather settle down young or wander forever?",
    "Would you rather inherit wealth or build it from nothing?",
    
    # Social Media Reality
    "Would you rather have 1 million followers who don't care or 100 who genuinely support you?",
    "Would you rather go viral for something cringe or never get attention?",
    "Would you rather delete all social media or only communicate through social media?",
    "Would you rather post your life constantly or lurk forever?",
    "Would you rather have a perfect online life but sad real life or the opposite?",
    "Would you rather get canceled for something you said or never have a platform?",
    "Would you rather be social media famous or rich in real life but unknown online?",
    "Would you rather have an aesthetic life for content or messy life that's real?",
    "Would you rather everyone see your screen time or your bank account?",
    "Would you rather post unfiltered and get judged or curate everything and feel fake?",
    
    # Brutal Honesty vs Comfort
    "Would you rather hear the brutal truth or a comforting lie?",
    "Would you rather be told you're annoying or never know?",
    "Would you rather someone tell you your outfit is ugly or let you go out like that?",
    "Would you rather know if you're the problem or stay oblivious?",
    "Would you rather your friends be honest and hurt you or lie to protect you?",
    "Would you rather find out you're hated or think you're liked when you're not?",
    "Would you rather be told you're being toxic or lose friends without knowing why?",
    "Would you rather hear what your ex really thinks or move on in peace?",
    "Would you rather know your flaws or live confidently ignorant?",
    "Would you rather someone tell you they're not interested or ghost you?",
    
    # Time & Memory Tradeoffs
    "Would you rather relive your best year forever or experience new mediocre years?",
    "Would you rather forget your worst memory or your best one?",
    "Would you rather go back and redo high school or skip to 30?",
    "Would you rather remember every conversation or forget everything after a week?",
    "Would you rather live one perfect day on repeat or normal unpredictable days?",
    "Would you rather age slower but watch everyone age normal or age normal with everyone?",
    "Would you rather pause time but still age or not age but time moves?",
    "Would you rather go back and warn your past self or get advice from your future self?",
    "Would you rather skip to the good parts of life or experience it all?",
    "Would you rather remember every mistake forever or forget but keep making the same ones?",
    
    # Success vs Happiness
    "Would you rather be successful and stressed or unsuccessful and at peace?",
    "Would you rather achieve your dream but lose relationships or keep relationships but never achieve it?",
    "Would you rather be famous and exhausted or unknown and relaxed?",
    "Would you rather win but feel empty or lose but be proud of trying?",
    "Would you rather have everything you want but feel nothing or have nothing but feel everything?",
    "Would you rather achieve greatness young and peak early or slowly build to it?",
    "Would you rather be the best and lonely or average with good company?",
    "Would you rather be respected for what you do or loved for who you are?",
    "Would you rather live to work or work to live?",
    "Would you rather have eternal motivation but never rest or relaxed but no drive?",
    
    # Loyalty Tests
    "Would you rather betray a friend for your own gain or stay loyal and lose?",
    "Would you rather your best friend date your ex or date your crush?",
    "Would you rather defend your friend even when they're wrong or call them out?",
    "Would you rather keep a secret that hurts someone or tell and break trust?",
    "Would you rather stay loyal to your roots or leave them for better opportunities?",
    "Would you rather choose family over friends or friends over family?",
    "Would you rather forgive a betrayal or cut them off forever?",
    "Would you rather be the backup friend or have no friends?",
    "Would you rather your friend succeed beyond you or fail with you?",
    "Would you rather lose a friend by being honest or keep them by lying?",
    
    # Mental Health Realities
    "Would you rather deal with anxiety or depression?",
    "Would you rather feel everything intensely or feel nothing at all?",
    "Would you rather be happy but delusional or aware but miserable?",
    "Would you rather overshare your problems or bottle everything up?",
    "Would you rather be the friend who needs help or the one always helping?",
    "Would you rather go to therapy but be judged or struggle alone?",
    "Would you rather be called dramatic or emotionally unavailable?",
    "Would you rather cry easily or never be able to cry?",
    "Would you rather feel too much or not enough?",
    "Would you rather people know you're struggling or think you're fine when you're not?",
    
    # Moral Gray Areas
    "Would you rather steal from a corporation or let someone hungry go without?",
    "Would you rather lie to protect someone or tell the truth and hurt them?",
    "Would you rather snitch on a friend doing something wrong or stay quiet?",
    "Would you rather help someone who wouldn't help you or prioritize yourself?",
    "Would you rather take credit you don't deserve or let someone take yours?",
    "Would you rather do something unethical for survival or struggle with morals intact?",
    "Would you rather expose someone's wrongdoing or mind your business?",
    "Would you rather benefit from someone else's failure or miss your chance?",
    "Would you rather forgive something unforgivable or hold a grudge forever?",
    "Would you rather be manipulative to get ahead or honest and left behind?",
]

# ==================== SPARK DEBATES ====================

SPARK_DEBATES = [
    # Real Social Dilemmas
    "Should you tell your friend their partner is cheating if you only heard it secondhand?",
    "Is ghosting someone ever justified?",
    "Should you stay friends with someone who wronged your other friend?",
    "Is it worse to cheat on a test or to let someone copy off you?",
    "Should you call out a friend for lying even if it's about something small?",
    "Is it okay to date your friend's ex if they say they're over it?",
    "Should you forgive someone who apologized but clearly doesn't mean it?",
    "Is venting about someone behind their back the same as talking shit?",
    "Should you tell someone the truth if it will definitely hurt them?",
    "Is it wrong to cut people off without explanation?",
    "Should loyalty mean agreeing with your friend even when they're wrong?",
    "Is canceling plans last minute ever not rude?",
    "Should you stay friends with someone just because you've known them forever?",
    "Is keeping a secret from your best friend ever okay?",
    "Should you defend your friend even if they're objectively wrong?",
    "Is it okay to like someone's ex if you asked permission first?",
    "Should you warn someone if you know they're about to embarrass themselves?",
    "Is borrowing money from friends ever a good idea?",
    "Should you tell your friend you don't like their new partner?",
    "Is subtweeting about someone worse than confronting them directly?",
    
    # Career & Money
    "Is nepotism wrong if everyone does it?",
    "Should you take credit for group work if you did most of it?",
    "Is lying on your resume okay if everyone else does it?",
    "Should you quit a job you hate even if you need the money?",
    "Is asking about salary on the first date a red flag?",
    "Should you tell your coworkers how much you make?",
    "Is it wrong to flex your wealth online?",
    "Should you lend money to family knowing they won't pay you back?",
    "Is working a job you're overqualified for embarrassing?",
    "Should you report a coworker for slacking if it affects you?",
    
    # Relationships & Dating
    "Is checking your partner's phone ever justified?",
    "Should you tell someone why you're rejecting them?",
    "Is staying friends with your ex realistic or delusional?",
    "Should you date someone your friend had a crush on?",
    "Is emotional cheating as bad as physical cheating?",
    "Should you lower your standards if you keep getting rejected?",
    "Is sliding into DMs creepy or confident?",
    "Should you warn someone their partner is toxic even if they won't listen?",
    "Is breaking up over text ever acceptable?",
    "Should you tell your partner about past hookups?",
    "Is asking to split the bill on a first date a red flag?",
    "Should you stay in a relationship that's good but not great?",
    "Is love bombing a red flag or just enthusiasm?",
    "Should you date someone your parent doesn't approve of?",
    "Is orbiting an ex on social media harmless or weird?",
    
    # Social Media & Online
    "Should you unfollow someone after an argument?",
    "Is posting thirst traps while in a relationship disrespectful?",
    "Should you accept follow requests from people you barely know?",
    "Is vagueposting immature or cathartic?",
    "Should you call out misinformation even if it starts drama?",
    "Is lurking without liking posts okay or weird?",
    "Should you curate your online persona or be completely authentic?",
    "Is archive-stalking an ex moving on or unhealthy?",
    "Should you delete old embarrassing posts or own them?",
    "Is posting about your relationship too much a red flag?",
    
    # Life Choices
    "Should you move for a job opportunity if it means leaving everyone?",
    "Is taking a gap year lazy or smart?",
    "Should you go to therapy even if you think you're fine?",
    "Is choosing career over relationships selfish?",
    "Should you pursue a passion that'll probably fail financially?",
    "Is cutting off family ever justified?",
    "Should you stay in your hometown or leave to grow?",
    "Is doing something just for money selling out?",
    "Should you change yourself to fit in somewhere?",
    "Is copying someone's style flattery or theft?",
    
    # Moral & Ethics (Casual)
    "Is stealing from corporations less wrong than stealing from people?",
    "Should you return extra change if a cashier gave you too much?",
    "Is buying fake designer stuff lying?",
    "Should you snitch even if there's a no-snitch culture?",
    "Is pirating content from big companies victimless?",
    "Should you help someone who wouldn't help you?",
    "Is staying neutral in an argument between friends taking a side?",
    "Should you speak up if you see something wrong but it doesn't affect you?",
    "Is revenge ever justified?",
    "Should you tell the truth if lying would spare someone's feelings?",
    
    # Group Dynamics
    "Should the friend group kick someone out if they're toxic?",
    "Is being the therapist friend a choice or a burden?",
    "Should you call out problematic jokes in the friend group?",
    "Is it okay to have a favorite person in the friend group?",
    "Should everyone pay equally or pay for what they ordered?",
    "Is excluding one person to avoid drama justified?",
    "Should the group always wait for the late friend?",
    "Is planning things without inviting everyone okay sometimes?",
    "Should you tell someone they're not invited if they ask?",
    "Is forcing participation in group activities toxic positivity?",
    
    # Self & Identity
    "Is changing your entire personality for someone you like authentic or fake?",
    "Should you call people out for misgendering if it's an honest mistake?",
    "Is faking confidence until you make it lying to yourself?",
    "Should you change your interests to fit in with new friends?",
    "Is reinventing yourself growth or running away?",
    "Should you hide parts of yourself to avoid judgment?",
    "Is self-deprecating humor unhealthy or relatable?",
    "Should you pursue aesthetics you like even if they don't suit you?",
    "Is code-switching necessary or inauthentic?",
    "Should you force yourself to be more social?",
    
    # Communication Style
    "Is leaving someone on read worse than saying you're busy?",
    "Should you always reply to messages even from people you don't like?",
    "Is being brutally honest harsh or helpful?",
    "Should you confront issues immediately or let them cool down?",
    "Is double texting desperate or persistent?",
    "Should you explain yourself when you cancel plans?",
    "Is asking 'can we talk' stressful or considerate?",
    "Should you respond to a drunk text when they're sober?",
    "Is ignoring negativity peaceful or avoiding conflict?",
    "Should you always say yes when someone asks if you're okay?",
    
    # Success & Ambition
    "Is bragging about achievements confidence or arrogance?",
    "Should you take opportunities that come from privilege?",
    "Is comparing yourself to others motivation or toxic?",
    "Should you support friends' unrealistic dreams?",
    "Is settling for less practical or giving up?",
    "Should you fake it till you make it or be humble?",
    "Is working constantly dedication or workaholism?",
    "Should you compete with friends or just support them?",
    "Is wanting more always ambition or greed?",
    "Should you change your goals based on what's achievable?",
    
    # Conflict Resolution
    "Is apologizing first weak or mature?",
    "Should you forgive and forget or forgive but remember?",
    "Is staying mad about small things petty or having standards?",
    "Should you bring up old issues during new arguments?",
    "Is the silent treatment a boundary or manipulation?",
    "Should you apologize even if you don't think you're wrong?",
    "Is demanding an apology valid or controlling?",
    "Should you give someone the benefit of the doubt or trust your gut?",
    "Is holding grudges protecting yourself or being bitter?",
    "Should you move on without closure?",
    
    # Trust & Honesty
    "Is checking facts before believing gossip paranoid or smart?",
    "Should you always assume positive intent?",
    "Is hiding something the same as lying?",
    "Should you admit when you're wrong immediately?",
    "Is white lying protecting feelings or being fake?",
    "Should you trust actions or words more?",
    "Is being skeptical of everyone healthy or toxic?",
    "Should you give chances to people who burned you before?",
    "Is oversharing authentic or trauma dumping?",
    "Should you believe apologies or wait for changed behavior?",
    
    # Boundaries & Self-Care
    "Is saying no to people rude or setting boundaries?",
    "Should you help friends even when you're struggling?",
    "Is taking time for yourself selfish during a crisis?",
    "Should you ghost toxic people or explain why you're leaving?",
    "Is prioritizing mental health over obligations valid?",
    "Should you force yourself to socialize when you don't want to?",
    "Is cutting people off protecting yourself or running away?",
    "Should you lower boundaries to keep friends?",
    "Is being unavailable sometimes healthy or flaky?",
    "Should you always be there for people who need you?",
    
    # Social Expectations
    "Is small talk necessary or pointless?",
    "Should you laugh at jokes you don't find funny?",
    "Is dressing up for going out tryhard or respecting the occasion?",
    "Should you pretend to like people you don't?",
    "Is showing up empty-handed to a party okay?",
    "Should you go to events you're invited to out of obligation?",
    "Is bringing a plus-one without asking acceptable?",
    "Should you thank people for doing the bare minimum?",
    "Is initiating plans always or should it be mutual?",
    "Should you hide your mood to not bring others down?",
    
    # Risk & Fear
    "Is playing it safe smart or cowardly?",
    "Should you try something even if you'll probably fail?",
    "Is fear of judgment holding you back or protecting you?",
    "Should you take risks that could hurt people you love?",
    "Is avoiding confrontation peaceful or cowardly?",
    "Should you do something scary just to prove you can?",
    "Is overthinking protecting you or paralyzing you?",
    "Should you bet on yourself even when odds are against you?",
    "Is walking away from a challenge quitting or being smart?",
    "Should you always have a backup plan?",
    
    # Fairness & Justice
    "Is treating everyone equally fair or ignoring different needs?",
    "Should you call out injustice even if it doesn't affect you?",
    "Is being neutral in conflicts taking the moral high ground or cowardly?",
    "Should punishment match the crime or the impact?",
    "Is giving favors expecting something back transactional or fair?",
    "Should second chances be unlimited?",
    "Is treating people how they treat you petty or fair?",
    "Should you demand reciprocity in relationships?",
    "Is refusing to forgive holding yourself back or having standards?",
    "Should everyone get the same opportunities or the best person?",
    
    # Judgment & Perspective
    "Is judging people based on first impressions shallow or intuitive?",
    "Should you separate the art from the artist?",
    "Is caring what others think weak or human?",
    "Should you defend people who can't defend themselves?",
    "Is assuming the worst about people realistic or cynical?",
    "Should you mind your business or speak up?",
    "Is giving unsolicited advice helpful or annoying?",
    "Should you call out hypocrisy even in yourself?",
    "Is it hypocritical to criticize something you also do?",
    "Should you hold yourself to the same standards you hold others?",
    
    # Growth & Change
    "Is changing for someone growth or losing yourself?",
    "Should you apologize for who you used to be?",
    "Is outgrowing friends sad but natural or avoidable?",
    "Should you confront your past or move forward?",
    "Is staying consistent authentic or refusing to grow?",
    "Should you reinvent yourself after a breakup?",
    "Is documenting your growth online inspiring or performative?",
    "Should you stay connected to your roots or embrace change?",
    "Is changing your mind flip-flopping or evolving?",
    "Should you force personal growth or let it happen naturally?",
]

# ==================== BUTTON QUESTIONS ====================

BUTTON_QUESTIONS = [
    # Social Consequences
    "Would you press a button that makes everyone like you but nobody truly knows you?",
    "Would you press a button that erases your most embarrassing memory but also your proudest?",
    "Would you press a button that makes you charismatic but you can tell everyone's faking around you?",
    "Would you press a button that gives you a million followers but they're all bots?",
    "Would you press a button that lets you read minds but you can't turn it off?",
    "Would you press a button that makes you the main character but your life is dramatic forever?",
    "Would you press a button that makes you always right in arguments but nobody likes debating you?",
    "Would you press a button that shows you what everyone thinks of you but you can't change their minds?",
    "Would you press a button that lets you redo one conversation but you forget the original?",
    "Would you press a button that makes you unforgettable but nobody makes new memories with you?",
    
    # Relationship Costs
    "Would you press a button that shows you your soulmate but they're already taken?",
    "Would you press a button that makes anyone fall for you but they'll leave in exactly one year?",
    "Would you press a button that prevents heartbreak but you can never fall deeply in love?",
    "Would you press a button that reunites you with your ex but erases all the bad memories?",
    "Would you press a button that makes your crush like you back but ruins your friend's chance with them?",
    "Would you press a button that lets you know if your relationship will last but ruins the mystery?",
    "Would you press a button that fixes your relationship but you can never break up?",
    "Would you press a button that makes you attractive to everyone but your personality becomes bland?",
    "Would you press a button that shows you all your future relationships but spoils the surprise?",
    "Would you press a button that makes you the perfect partner but you lose your sense of self?",
    
    # Career & Success Costs
    "Would you press a button that gives you your dream job but you can't have a personal life?",
    "Would you press a button that makes you famous but everyone knows your search history?",
    "Would you press a button that guarantees success but you can never credit anyone who helped?",
    "Would you press a button that makes you rich but everyone thinks you didn't earn it?",
    "Would you press a button that makes you brilliant but socially awkward?",
    "Would you press a button that gives you career success but you lose your hobbies?",
    "Would you press a button that makes you the best at one thing but mediocre at everything else?",
    "Would you press a button that gives you a million dollars but your best friend loses their job?",
    "Would you press a button that makes you respected professionally but your personal life falls apart?",
    "Would you press a button that lets you retire at 30 but you get bored forever?",
    
    # Memory & Knowledge Costs
    "Would you press a button that lets you forget anything but it's random what you lose?",
    "Would you press a button that gives you perfect memory but you can't forget trauma?",
    "Would you press a button that shows you how you die but you can't change it?",
    "Would you press a button that lets you relive your best memory but makes current life feel dull?",
    "Would you press a button that makes you fluent in all languages but you forget your native one?",
    "Would you press a button that answers any question but takes a year off your life per answer?",
    "Would you press a button that shows you your future but you must live it out knowing what happens?",
    "Would you press a button that lets you learn anything instantly but you can't enjoy the process?",
    "Would you press a button that removes all your regrets but also all the lessons learned?",
    "Would you press a button that shows you what your life would be like with different choices but you're stuck with this one?",
    
    # Friendship Costs
    "Would you press a button that makes your friends always available but they have no other friends?",
    "Would you press a button that reveals which friends are fake but you can't confront them?",
    "Would you press a button that makes you popular but your best friend gets left behind?",
    "Would you press a button that guarantees lifelong friends but you can never make new ones?",
    "Would you press a button that fixes one friendship but damages another random one?",
    "Would you press a button that makes people confide in you but you have nobody to confide in?",
    "Would you press a button that shows you who your real friends are but they all leave immediately?",
    "Would you press a button that makes you the therapist friend but nobody asks how you're doing?",
    "Would you press a button that prevents friend drama but your friendships stay surface level?",
    "Would you press a button that makes you everyone's favorite but nobody's best friend?",
    
    # Time & Life Tradeoffs
    "Would you press a button that adds 20 years to your life but you spend them alone?",
    "Would you press a button that lets you relive your 20s but everyone else ages normally?",
    "Would you press a button that fast-forwards you 5 years but you have no memory of what you missed?",
    "Would you press a button that pauses your aging but you watch everyone else grow old?",
    "Would you press a button that shows you your life's purpose but forces you to follow it?",
    "Would you press a button that lets you go back and fix one mistake but creates a new random one?",
    "Would you press a button that makes every day exciting but exhausting?",
    "Would you press a button that gives you more time but makes it feel slower?",
    "Would you press a button that lets you skip bad days but also randomly skips good ones?",
    "Would you press a button that makes you live twice as long but everything moves at half speed?",
    
    # Mental & Emotional Costs
    "Would you press a button that removes anxiety but also removes your caution?",
    "Would you press a button that makes you confident but delusional?",
    "Would you press a button that prevents sadness but also prevents deep joy?",
    "Would you press a button that makes you stop caring what people think but you become insensitive?",
    "Would you press a button that removes all negative emotions but makes you feel shallow?",
    "Would you press a button that gives you closure on everything but you can't move forward?",
    "Would you press a button that makes you fearless but reckless?",
    "Would you press a button that lets you control your emotions but they feel forced?",
    "Would you press a button that stops overthinking but you miss important details?",
    "Would you press a button that makes you happy all the time but nothing feels meaningful?",
    
    # Personal Growth Costs
    "Would you press a button that makes you instantly mature but you skip your youth?",
    "Would you press a button that gives you wisdom but you lose your sense of wonder?",
    "Would you press a button that fixes all your flaws but removes what makes you unique?",
    "Would you press a button that makes you always learn from mistakes but you feel every regret intensely?",
    "Would you press a button that makes you disciplined but spontaneity dies?",
    "Would you press a button that makes you successful but you can't enjoy the journey?",
    "Would you press a button that makes you grow faster but you outgrow everyone?",
    "Would you press a button that removes your insecurities but also your drive to improve?",
    "Would you press a button that makes you self-aware but hyper-critical?",
    "Would you press a button that fast-tracks your personal growth but it's painful?",
    
    # Truth & Reality Costs
    "Would you press a button that shows you the truth about everything but you can't share it?",
    "Would you press a button that makes you see people's true intentions but you can never trust again?",
    "Would you press a button that removes all lies from your life but ruins comfortable ignorance?",
    "Would you press a button that shows you your biggest flaw but you can't fix it?",
    "Would you press a button that makes you brutally honest but people avoid you?",
    "Would you press a button that shows you who talks about you but you can't confront them?",
    "Would you press a button that reveals all secrets but including your own?",
    "Would you press a button that shows you reality without filters but it's depressing?",
    "Would you press a button that makes you allergic to lies but people lie to spare you?",
    "Would you press a button that shows you who you'll become but you don't like it?",
    
    # Power & Control Costs
    "Would you press a button that lets you control one person but they control you back?",
    "Would you press a button that gives you power over time but everything else is random?",
    "Would you press a button that makes you lucky but someone close to you becomes unlucky?",
    "Would you press a button that lets you influence people but you can't be influenced?",
    "Would you press a button that makes you invincible but you feel no physical sensations?",
    "Would you press a button that gives you authority but everyone resents you?",
    "Would you press a button that lets you fix one global problem but you're blamed for the consequences?",
    "Would you press a button that gives you unlimited resources but you must share them?",
    "Would you press a button that makes you the smartest person but nobody understands you?",
    "Would you press a button that grants you influence but steals your privacy?",
    
    # Communication Consequences  
    "Would you press a button that makes you persuasive but you can't tell if people genuinely agree?",
    "Would you press a button that lets you speak any language but you stutter in your native one?",
    "Would you press a button that makes you witty but people don't take you seriously?",
    "Would you press a button that lets you always say the right thing but it never feels authentic?",
    "Would you press a button that prevents you from lying but also from keeping secrets?",
    "Would you press a button that makes your words powerful but you can't take them back?",
    "Would you press a button that lets you communicate telepathically but everyone can hear you too?",
    "Would you press a button that makes you a great listener but nobody listens to you?",
    "Would you press a button that lets you always win debates but people avoid talking to you?",
    "Would you press a button that makes you eloquent but you lose your casual speech?",
]
