"""v1.64 Questions - Casual, sharp, socially-relevant"""

FRIEND_GROUP_QUESTIONS_V164 = [
    "Who here is most likely to become famous for something weird?",
    "Who here is most likely to survive a zombie apocalypse?",
    "Who here is most likely to accidentally start a cult?",
    "Who here is most likely to win an argument they're wrong about?",
    "Who here is most likely to get away with a crime?",
    "Who here is most likely to become a villain in their origin story?",
    "Who here is most likely to fake their own death for fun?",
    "Who here is most likely to get canceled on Twitter?",
    "Who here is most likely to betray the group for $1 million?",
    "Who here is most likely to gaslight someone accidentally?",
    "Who here is most likely to become a cult leader?",
    "Who here is most likely to have a secret nobody knows?",
    "Who here is most likely to overthrow a government?",
    "Who here is most likely to get kidnapped and befriend the kidnapper?",
    "Who here is most likely to cause an international incident?",
    "Who here is most likely to start a ponzi scheme?",
    "Who here is most likely to join a pyramid scheme?",
    "Who here is most likely to go viral for the wrong reasons?",
    "Who here is most likely to catfish someone by accident?",
    "Who here is most likely to win a fight they shouldn't?",
    "Who here is most likely to talk their way out of prison?",
    "Who here is most likely to become a supervillain?",
    "Who here is most likely to fake being sick to skip something?",
    "Who here is most likely to lie on their resume?",
    "Who here is most likely to overthink a text for an hour?",
    "Who here is most likely to drop everything for someone they just met?",
    "Who here is most likely to have a villain arc?",
    "Who here is most likely to manipulate someone without realizing?",
    "Who here is most likely to start a revolution?",
    "Who here is most likely to become a conspiracy theorist?",
    "Who here is most likely to get caught up in drama they didn't start?",
    "Who here is most likely to ruin a surprise party?",
    "Who here is most likely to get lost in their own neighborhood?",
    "Who here is most likely to bring a knife to a gunfight and win?",
    "Who here is most likely to die first in a horror movie?",
    "Who here is most likely to survive purely out of spite?",
    "Who here is most likely to fake an accent for no reason?",
    "Who here is most likely to commit tax fraud?",
    "Who here is most likely to run away and join the circus?",
    "Who here is most likely to become a TikTok influencer?",
    "Who here is most likely to ghost someone they've known for years?",
    "Who here is most likely to write an exposé about this friend group?",
    "Who here is most likely to sell out for brand deals?",
    "Who here is most likely to marry rich?",
    "Who here is most likely to become a hermit?",
    "Who here is most likely to fake their way into a career?",
    "Who here is most likely to start beef with a celebrity?",
    "Who here is most likely to become internet famous overnight?",
    "Who here is most likely to go off the grid?",
    "Who here is most likely to accidentally commit a felony?",
    "Who here is most likely to cry at a Pixar movie?",
    "Who here is most likely to get banned from a public place?",
    "Who here is most likely to start a fight over nothing?",
    "Who here is most likely to become a cryptobro?",
    "Who here is most likely to join a commune?",
    "Who here is most likely to have main character syndrome?",
    "Who here is most likely to fake being rich?",
    "Who here is most likely to become a standup comedian?",
    "Who here is most likely to blackmail someone?",
    "Who here is most likely to leak the group chat?",
    "Who here is most likely to scam someone accidentally?",
    "Who here is most likely to argue with a wall and lose?",
    "Who here is most likely to start a podcast nobody listens to?",
    "Who here is most likely to become a professional gambler?",
    "Who here is most likely to get arrested for something stupid?",
    "Who here is most likely to become a cult member?",
    "Who here is most likely to fake an injury for attention?",
    "Who here is most likely to start a YouTube channel and give up in a week?",
    "Who here is most likely to become a karen?",
    "Who here is most likely to create fake drama for content?",
    "Who here is most likely to get famous and forget about everyone?",
    "Who here is most likely to go viral for something embarrassing?",
    "Who here is most likely to become a politician?",
    "Who here is most likely to start a bar fight?",
    "Who here is most likely to get into MLM?",
    "Who here is most likely to catfish online?",
    "Who here is most likely to become a hacker?",
    "Who here is most likely to develop a god complex?",
    "Who here is most likely to get exposed in a documentary?",
    "Who here is most likely to have a burner account?",
    "Who here is most likely to fake their death on social media?",
    "Who here is most likely to become a true crime podcast host?",
    "Who here is most likely to accidentally become a meme?",
    "Who here is most likely to get doxxed?",
    "Who here is most likely to start drama in the group chat?",
    "Who here is most likely to rage quit something important?",
    "Who here is most likely to become an influencer's worst nightmare?",
    "Who here is most likely to get into a Twitter fight with their employer?",
    "Who here is most likely to impulse buy something ridiculous?",
    "Who here is most likely to become a motivational speaker?",
    "Who here is most likely to get kicked out of a Discord server?",
    "Who here is most likely to troll someone too hard?",
    "Who here is most likely to delete their account after one bad take?",
    "Who here is most likely to become internet infamous?",
    "Who here is most likely to accidentally reveal a secret?",
    "Who here is most likely to start a rumor?",
    "Who here is most likely to win a reality TV show?",
    "Who here is most likely to get in trouble for arguing online?",
    "Who here is most likely to be the subject of a true crime documentary?",
    "Who here is most likely to fake cry to get out of trouble?",
]

SPARK_DEBATES_V164 = [
    # Real Social Dilemmas
    "Should you tell your friend their partner is cheating if you only heard it secondhand?",
    "Is ghosting someone ever justified?",
    "Should you stay friends with someone who wronged your other friend?",
    "Is it worse to cheat on a test or to let someone copy off you?",
    "Should you call out a friend for lying even if it's about something small?",
    "Is it okay to date your friend's ex if they say they're over it?",
    "Should you forgive someone who apologized but clearly doesn't mean it?",
    "Is venting about someone behind their back the same as talking shit?",
    "Should you tell someone the truth if it will definitely hurt them?",
    "Is it wrong to cut people off without explanation?",
    "Should loyalty mean agreeing with your friend even when they're wrong?",
    "Is canceling plans last minute ever not rude?",
    "Should you stay friends with someone just because you've known them forever?",
    "Is keeping a secret from your best friend ever okay?",
    "Should you defend your friend even if they're objectively wrong?",
    "Is it okay to like someone's ex if you asked permission first?",
    "Should you warn someone if you know they're about to embarrass themselves?",
    "Is borrowing money from friends ever a good idea?",
    "Should you tell your friend you don't like their new partner?",
    "Is subtweeting about someone worse than confronting them directly?",
    
    # Career & Money
    "Is nepotism wrong if everyone does it?",
    "Should you take credit for group work if you did most of it?",
    "Is lying on your resume okay if everyone else does it?",
    "Should you quit a job you hate even if you need the money?",
    "Is asking about salary on the first date a red flag?",
    "Should you tell your coworkers how much you make?",
    "Is it wrong to flex your wealth online?",
    "Should you lend money to family knowing they won't pay you back?",
    "Is working a job you're overqualified for embarrassing?",
    "Should you report a coworker for slacking if it affects you?",
    
    # Relationships & Dating
    "Is checking your partner's phone ever justified?",
    "Should you tell someone why you're rejecting them?",
    "Is staying friends with your ex realistic or delusional?",
    "Should you date someone your friend had a crush on?",
    "Is emotional cheating as bad as physical cheating?",
    "Should you lower your standards if you keep getting rejected?",
    "Is sliding into DMs creepy or confident?",
    "Should you warn someone their partner is toxic even if they won't listen?",
    "Is breaking up over text ever acceptable?",
    "Should you tell your partner about past hookups?",
    "Is asking to split the bill on a first date a red flag?",
    "Should you stay in a relationship that's good but not great?",
    "Is love bombing a red flag or just enthusiasm?",
    "Should you date someone your parent doesn't approve of?",
    "Is orbiting an ex on social media harmless or weird?",
    
    # Social Media & Online
    "Should you unfollow someone after an argument?",
    "Is posting thirst traps while in a relationship disrespectful?",
    "Should you accept follow requests from people you barely know?",
    "Is vagueposting immature or cathartic?",
    "Should you call out misinformation even if it starts drama?",
    "Is lurking without liking posts okay or weird?",
    "Should you curate your online persona or be completely authentic?",
    "Is archive-stalking an ex moving on or unhealthy?",
    "Should you delete old embarrassing posts or own them?",
    "Is posting about your relationship too much a red flag?",
    
    # Life Choices
    "Should you move for a job opportunity if it means leaving everyone?",
    "Is taking a gap year lazy or smart?",
    "Should you go to therapy even if you think you're fine?",
    "Is choosing career over relationships selfish?",
    "Should you pursue a passion that'll probably fail financially?",
    "Is cutting off family ever justified?",
    "Should you stay in your hometown or leave to grow?",
    "Is doing something just for money selling out?",
    "Should you change yourself to fit in somewhere?",
    "Is copying someone's style flattery or theft?",
    
    # Moral & Ethics (Casual)
    "Is stealing from corporations less wrong than stealing from people?",
    "Should you return extra change if a cashier gave you too much?",
    "Is buying fake designer stuff lying?",
    "Should you snitch even if there's a no-snitch culture?",
    "Is pirating content from big companies victimless?",
    "Should you help someone who wouldn't help you?",
    "Is staying neutral in an argument between friends taking a side?",
    "Should you speak up if you see something wrong but it doesn't affect you?",
    "Is revenge ever justified?",
    "Should you tell the truth if lying would spare someone's feelings?",
    
    # Group Dynamics
    "Should the friend group kick someone out if they're toxic?",
    "Is being the therapist friend a choice or a burden?",
    "Should you call out problematic jokes in the friend group?",
    "Is it okay to have a favorite person in the friend group?",
    "Should everyone pay equally or pay for what they ordered?",
    "Is excluding one person to avoid drama justified?",
    "Should the group always wait for the late friend?",
    "Is planning things without inviting everyone okay sometimes?",
    "Should you tell someone they're not invited if they ask?",
    "Is forcing participation in group activities toxic positivity?",
    
    # Self & Identity
    "Is changing your entire personality for someone you like authentic or fake?",
    "Should you call people out for misgendering if it's an honest mistake?",
    "Is faking confidence until you make it lying to yourself?",
    "Should you change your interests to fit in with new friends?",
    "Is reinventing yourself growth or running away?",
    "Should you hide parts of yourself to avoid judgment?",
    "Is self-deprecating humor unhealthy or relatable?",
    "Should you pursue aesthetics you like even if they don't suit you?",
    "Is code-switching necessary or inauthentic?",
    "Should you force yourself to be more social?",
    
    # Communication Style
    "Is leaving someone on read worse than saying you're busy?",
    "Should you always reply to messages even from people you don't like?",
    "Is being brutally honest harsh or helpful?",
    "Should you confront issues immediately or let them cool down?",
    "Is double texting desperate or persistent?",
    "Should you explain yourself when you cancel plans?",
    "Is asking 'can we talk' stressful or considerate?",
    "Should you respond to a drunk text when they're sober?",
    "Is ignoring negativity peaceful or avoiding conflict?",
    "Should you always say yes when someone asks if you're okay?",
    
    # Success & Ambition
    "Is bragging about achievements confidence or arrogance?",
    "Should you take opportunities that come from privilege?",
    "Is comparing yourself to others motivation or toxic?",
    "Should you support friends' unrealistic dreams?",
    "Is settling for less practical or giving up?",
    "Should you fake it till you make it or be humble?",
    "Is working constantly dedication or workaholism?",
    "Should you compete with friends or just support them?",
    "Is wanting more always ambition or greed?",
    "Should you change your goals based on what's achievable?",
    
    # Conflict Resolution
    "Is apologizing first weak or mature?",
    "Should you forgive and forget or forgive but remember?",
    "Is staying mad about small things petty or having standards?",
    "Should you bring up old issues during new arguments?",
    "Is the silent treatment a boundary or manipulation?",
    "Should you apologize even if you don't think you're wrong?",
    "Is demanding an apology valid or controlling?",
    "Should you give someone the benefit of the doubt or trust your gut?",
    "Is holding grudges protecting yourself or being bitter?",
    "Should you move on without closure?",
    
    # Trust & Honesty
    "Is checking facts before believing gossip paranoid or smart?",
    "Should you always assume positive intent?",
    "Is hiding something the same as lying?",
    "Should you admit when you're wrong immediately?",
    "Is white lying protecting feelings or being fake?",
    "Should you trust actions or words more?",
    "Is being skeptical of everyone healthy or toxic?",
    "Should you give chances to people who burned you before?",
    "Is oversharing authentic or trauma dumping?",
    "Should you believe apologies or wait for changed behavior?",
    
    # Boundaries & Self-Care
    "Is saying no to people rude or setting boundaries?",
    "Should you help friends even when you're struggling?",
    "Is taking time for yourself selfish during a crisis?",
    "Should you ghost toxic people or explain why you're leaving?",
    "Is prioritizing mental health over obligations valid?",
    "Should you force yourself to socialize when you don't want to?",
    "Is cutting people off protecting yourself or running away?",
    "Should you lower boundaries to keep friends?",
    "Is being unavailable sometimes healthy or flaky?",
    "Should you always be there for people who need you?",
    
    # Social Expectations
    "Is small talk necessary or pointless?",
    "Should you laugh at jokes you don't find funny?",
    "Is dressing up for going out tryhard or respecting the occasion?",
    "Should you pretend to like people you don't?",
    "Is showing up empty-handed to a party okay?",
    "Should you go to events you're invited to out of obligation?",
    "Is bringing a plus-one without asking acceptable?",
    "Should you thank people for doing the bare minimum?",
    "Is initiating plans always or should it be mutual?",
    "Should you hide your mood to not bring others down?",
    
    # Risk & Fear
    "Is playing it safe smart or cowardly?",
    "Should you try something even if you'll probably fail?",
    "Is fear of judgment holding you back or protecting you?",
    "Should you take risks that could hurt people you love?",
    "Is avoiding confrontation peaceful or cowardly?",
    "Should you do something scary just to prove you can?",
    "Is overthinking protecting you or paralyzing you?",
    "Should you bet on yourself even when odds are against you?",
    "Is walking away from a challenge quitting or being smart?",
    "Should you always have a backup plan?",
    
    # Fairness & Justice
    "Is treating everyone equally fair or ignoring different needs?",
    "Should you call out injustice even if it doesn't affect you?",
    "Is being neutral in conflicts taking the moral high ground or cowardly?",
    "Should punishment match the crime or the impact?",
    "Is giving favors expecting something back transactional or fair?",
    "Should second chances be unlimited?",
    "Is treating people how they treat you petty or fair?",
    "Should you demand reciprocity in relationships?",
    "Is refusing to forgive holding yourself back or having standards?",
    "Should everyone get the same opportunities or the best person?",
    
    # Judgment & Perspective
    "Is judging people based on first impressions shallow or intuitive?",
    "Should you separate the art from the artist?",
    "Is caring what others think weak or human?",
    "Should you defend people who can't defend themselves?",
    "Is assuming the worst about people realistic or cynical?",
    "Should you mind your business or speak up?",
    "Is giving unsolicited advice helpful or annoying?",
    "Should you call out hypocrisy even in yourself?",
    "Is it hypocritical to criticize something you also do?",
    "Should you hold yourself to the same standards you hold others?",
    
    # Growth & Change
    "Is changing for someone growth or losing yourself?",
    "Should you apologize for who you used to be?",
    "Is outgrowing friends sad but natural or avoidable?",
    "Should you confront your past or move forward?",
    "Is staying consistent authentic or refusing to grow?",
    "Should you reinvent yourself after a breakup?",
    "Is documenting your growth online inspiring or performative?",
    "Should you stay connected to your roots or embrace change?",
    "Is changing your mind flip-flopping or evolving?",
    "Should you force personal growth or let it happen naturally?",
]

SPARK_WYR_V164 = [
    # Social Cost Dilemmas
    "Would you rather everyone forget you exist for a month or remember every embarrassing thing you've done?",
    "Would you rather never be able to apologize or never be able to forgive?",
    "Would you rather have to say everything you think out loud or never speak your mind?",
    "Would you rather be the one who always texts first or never get texts from anyone?",
    "Would you rather everyone read your DMs or your search history?",
    "Would you rather always be overdressed or always be underdressed?",
    "Would you rather people think you're boring or think you're too much?",
    "Would you rather be loved but not respected or respected but not loved?",
    "Would you rather have no privacy but loyal friends or total privacy but no close relationships?",
    "Would you rather be known for something embarrassing or not be known at all?",
    
    # Career & Money Tradeoffs
    "Would you rather make a lot of money doing something boring or little money doing what you love?",
    "Would you rather be your own broke boss or rich working for someone you hate?",
    "Would you rather work 80 hours a week making bank or 20 hours barely getting by?",
    "Would you rather get a job through nepotism or struggle to get one on merit?",
    "Would you rather have your dream job but never have work-life balance or hate your job but have all the free time?",
    "Would you rather be wildly successful at 50 or moderately successful now?",
    "Would you rather get promoted but everyone hates you or stay where you are but be liked?",
    "Would you rather retire early but poor or retire late but comfortable?",
    "Would you rather start a business that might fail or keep a stable job you hate?",
    "Would you rather work remote forever but lonely or in office with people but commuting?",
    
    # Relationship Sacrifices
    "Would you rather date someone you love who doesn't love you back or someone who loves you but you don't love?",
    "Would you rather be in a relationship with no chemistry or no emotional connection?",
    "Would you rather your partner be attractive but dumb or ugly but brilliant?",
    "Would you rather never fall in love again or fall in love but get heartbroken every time?",
    "Would you rather be with someone perfect for you but your family hates or someone your family loves but isn't right for you?",
    "Would you rather stay single forever or settle for someone mediocre?",
    "Would you rather know your partner is cheating or never find out?",
    "Would you rather date someone clingy or emotionally unavailable?",
    "Would you rather be with someone who's always right or always thinks they're right?",
    "Would you rather have a partner who's your best friend but no spark or passionate but toxic?",
    
    # Friend Group Dynamics
    "Would you rather have 100 fake friends or 1 real one?",
    "Would you rather be the least liked in a popular group or most liked in an unpopular group?",
    "Would you rather call out your friend and ruin the friendship or stay silent and resent them?",
    "Would you rather your friend group roast you or ignore you?",
    "Would you rather have friends who are fun but unreliable or boring but always there?",
    "Would you rather be the therapist friend or the comic relief?",
    "Would you rather have a friend who overshares or one who never shares anything?",
    "Would you rather lose a toxic friend or keep them to avoid drama?",
    "Would you rather be in a friend group where you're always left out of inside jokes or be the joke?",
    "Would you rather have friends who challenge you or friends who always agree?",
    
    # Personal Identity Tradeoffs
    "Would you rather be yourself and lonely or fake and popular?",
    "Would you rather hide your interests to fit in or be authentic and judged?",
    "Would you rather change everything about yourself and be happy or stay the same and miserable?",
    "Would you rather be known for your looks or your personality?",
    "Would you rather have everyone know your secrets or live a lie forever?",
    "Would you rather be average at everything or excellent at one thing but terrible at the rest?",
    "Would you rather have a boring life with no regrets or an exciting life full of mistakes?",
    "Would you rather be attractive but insecure or average but confident?",
    "Would you rather be book smart but socially awkward or street smart but academically behind?",
    "Would you rather be funny but never taken seriously or serious but boring?",
    
    # Communication Dilemmas
    "Would you rather never be able to text or only be able to communicate through text?",
    "Would you rather be left on read forever or get a harsh response?",
    "Would you rather always have to sugarcoat or always be brutally honest?",
    "Would you rather overshare everything or never open up?",
    "Would you rather argue every day or never voice disagreements?",
    "Would you rather give advice no one takes or never be asked for advice?",
    "Would you rather apologize for everything or never apologize?",
    "Would you rather people always misunderstand you or you always misunderstand them?",
    "Would you rather know what people say about you behind your back or never know?",
    "Would you rather be the person who ghosts or gets ghosted?",
    
    # Life Path Choices
    "Would you rather live in your hometown forever or move somewhere new but miss home?",
    "Would you rather pursue your dream and fail or not try and always wonder?",
    "Would you rather have a normal life with no drama or an exciting life with constant chaos?",
    "Would you rather go back and fix your past or see your future?",
    "Would you rather live fast and die young or live long but boring?",
    "Would you rather take the safe route and regret it or risk it all and fail?",
    "Would you rather be stuck in the past or anxious about the future?",
    "Would you rather have your life planned out or completely unpredictable?",
    "Would you rather settle down young or wander forever?",
    "Would you rather inherit wealth or build it from nothing?",
    
    # Social Media Reality
    "Would you rather have 1 million followers who don't care or 100 who genuinely support you?",
    "Would you rather go viral for something cringe or never get attention?",
    "Would you rather delete all social media or only communicate through social media?",
    "Would you rather post your life constantly or lurk forever?",
    "Would you rather have a perfect online life but sad real life or the opposite?",
    "Would you rather get canceled for something you said or never have a platform?",
    "Would you rather be social media famous or rich in real life but unknown online?",
    "Would you rather have an aesthetic life for content or messy life that's real?",
    "Would you rather everyone see your screen time or your bank account?",
    "Would you rather post unfiltered and get judged or curate everything and feel fake?",
    
    # Brutal Honesty vs Comfort
    "Would you rather hear the brutal truth or a comforting lie?",
    "Would you rather be told you're annoying or never know?",
    "Would you rather someone tell you your outfit is ugly or let you go out like that?",
    "Would you rather know if you're the problem or stay oblivious?",
    "Would you rather your friends be honest and hurt you or lie to protect you?",
    "Would you rather find out you're hated or think you're liked when you're not?",
    "Would you rather be told you're being toxic or lose friends without knowing why?",
    "Would you rather hear what your ex really thinks or move on in peace?",
    "Would you rather know your flaws or live confidently ignorant?",
    "Would you rather someone tell you they're not interested or ghost you?",
    
    # Time & Memory Tradeoffs
    "Would you rather relive your best year forever or experience new mediocre years?",
    "Would you rather forget your worst memory or your best one?",
    "Would you rather go back and redo high school or skip to 30?",
    "Would you rather remember every conversation or forget everything after a week?",
    "Would you rather live one perfect day on repeat or normal unpredictable days?",
    "Would you rather age slower but watch everyone age normal or age normal with everyone?",
    "Would you rather pause time but still age or not age but time moves?",
    "Would you rather go back and warn your past self or get advice from your future self?",
    "Would you rather skip to the good parts of life or experience it all?",
    "Would you rather remember every mistake forever or forget but keep making the same ones?",
    
    # Success vs Happiness
    "Would you rather be successful and stressed or unsuccessful and at peace?",
    "Would you rather achieve your dream but lose relationships or keep relationships but never achieve it?",
    "Would you rather be famous and exhausted or unknown and relaxed?",
    "Would you rather win but feel empty or lose but be proud of trying?",
    "Would you rather have everything you want but feel nothing or have nothing but feel everything?",
    "Would you rather achieve greatness young and peak early or slowly build to it?",
    "Would you rather be the best and lonely or average with good company?",
    "Would you rather be respected for what you do or loved for who you are?",
    "Would you rather live to work or work to live?",
    "Would you rather have eternal motivation but never rest or relaxed but no drive?",
    
    # Loyalty Tests
    "Would you rather betray a friend for your own gain or stay loyal and lose?",
    "Would you rather your best friend date your ex or date your crush?",
    "Would you rather defend your friend even when they're wrong or call them out?",
    "Would you rather keep a secret that hurts someone or tell and break trust?",
    "Would you rather stay loyal to your roots or leave them for better opportunities?",
    "Would you rather choose family over friends or friends over family?",
    "Would you rather forgive a betrayal or cut them off forever?",
    "Would you rather be the backup friend or have no friends?",
    "Would you rather your friend succeed beyond you or fail with you?",
    "Would you rather lose a friend by being honest or keep them by lying?",
    
    # Mental Health Realities
    "Would you rather deal with anxiety or depression?",
    "Would you rather feel everything intensely or feel nothing at all?",
    "Would you rather be happy but delusional or aware but miserable?",
    "Would you rather overshare your problems or bottle everything up?",
    "Would you rather be the friend who needs help or the one always helping?",
    "Would you rather go to therapy but be judged or struggle alone?",
    "Would you rather be called dramatic or emotionally unavailable?",
    "Would you rather cry easily or never be able to cry?",
    "Would you rather feel too much or not enough?",
    "Would you rather people know you're struggling or think you're fine when you're not?",
    
    # Moral Gray Areas
    "Would you rather steal from a corporation or let someone hungry go without?",
    "Would you rather lie to protect someone or tell the truth and hurt them?",
    "Would you rather snitch on a friend doing something wrong or stay quiet?",
    "Would you rather help someone who wouldn't help you or prioritize yourself?",
    "Would you rather take credit you don't deserve or let someone take yours?",
    "Would you rather do something unethical for survival or struggle with morals intact?",
    "Would you rather expose someone's wrongdoing or mind your business?",
    "Would you rather benefit from someone else's failure or miss your chance?",
    "Would you rather forgive something unforgivable or hold a grudge forever?",
    "Would you rather be manipulative to get ahead or honest and left behind?",
]

BUTTON_QUESTIONS_V164 = [
    # Social Consequences
    "Would you press a button that makes everyone like you but nobody truly knows you?",
    "Would you press a button that erases your most embarrassing memory but also your proudest?",
    "Would you press a button that makes you charismatic but you can tell everyone's faking around you?",
    "Would you press a button that gives you a million followers but they're all bots?",
    "Would you press a button that lets you read minds but you can't turn it off?",
    "Would you press a button that makes you the main character but your life is dramatic forever?",
    "Would you press a button that makes you always right in arguments but nobody likes debating you?",
    "Would you press a button that shows you what everyone thinks of you but you can't change their minds?",
    "Would you press a button that lets you redo one conversation but you forget the original?",
    "Would you press a button that makes you unforgettable but nobody makes new memories with you?",
    
    # Relationship Costs
    "Would you press a button that shows you your soulmate but they're already taken?",
    "Would you press a button that makes anyone fall for you but they'll leave in exactly one year?",
    "Would you press a button that prevents heartbreak but you can never fall deeply in love?",
    "Would you press a button that reunites you with your ex but erases all the bad memories?",
    "Would you press a button that makes your crush like you back but ruins your friend's chance with them?",
    "Would you press a button that lets you know if your relationship will last but ruins the mystery?",
    "Would you press a button that fixes your relationship but you can never break up?",
    "Would you press a button that makes you attractive to everyone but your personality becomes bland?",
    "Would you press a button that shows you all your future relationships but spoils the surprise?",
    "Would you press a button that makes you the perfect partner but you lose your sense of self?",
    
    # Career & Success Costs
    "Would you press a button that gives you your dream job but you can't have a personal life?",
    "Would you press a button that makes you famous but everyone knows your search history?",
    "Would you press a button that guarantees success but you can never credit anyone who helped?",
   "Would you press a button that makes you rich but everyone thinks you didn't earn it?",
    "Would you press a button that makes you brilliant but socially awkward?",
     "Would you press a button that gives you career success but you lose your hobbies?",
    "Would you press a button that makes you the best at one thing but mediocre at everything else?",
    "Would you press a button that gives you a million dollars but your best friend loses their job?",
    "Would you press a button that makes you respected professionally but your personal life falls apart?",
    "Would you press a button that lets you retire at 30 but you get bored forever?",
    
    # Memory & Knowledge Costs
    "Would you press a button that lets you forget anything but it's random what you lose?",
    "Would you press a button that gives you perfect memory but you can't forget trauma?",
    "Would you press a button that shows you how you die but you can't change it?",
    "Would you press a button that lets you relive your best memory but makes current life feel dull?",
    "Would you press a button that makes you fluent in all languages but you forget your native one?",
    "Would you press a button that answers any question but takes a year off your life per answer?",
    "Would you press a button that shows you your future but you must live it out knowing what happens?",
    "Would you press a button that lets you learn anything instantly but you can't enjoy the process?",
    "Would you press a button that removes all your regrets but also all the lessons learned?",
    "Would you press a button that shows you what your life would be like with different choices but you're stuck with this one?",
    
    # Friendship Costs
    "Would you press a button that makes your friends always available but they have no other friends?",
    "Would you press a button that reveals which friends are fake but you can't confront them?",
    "Would you press a button that makes you popular but your best friend gets left behind?",
    "Would you press a button that guarantees lifelong friends but you can never make new ones?",
    "Would you press a button that fixes one friendship but damages another random one?",
    "Would you press a button that makes people confide in you but you have nobody to confide in?",
    "Would you press a button that shows you who your real friends are but they all leave immediately?",
    "Would you press a button that makes you the therapist friend but nobody asks how you're doing?",
    "Would you press a button that prevents friend drama but your friendships stay surface level?",
    "Would you press a button that makes you everyone's favorite but nobody's best friend?",
    
    # Time & Life Tradeoffs
    "Would you press a button that adds 20 years to your life but you spend them alone?",
    "Would you press a button that lets you relive your 20s but everyone else ages normally?",
    "Would you press a button that fast-forwards you 5 years but you have no memory of what you missed?",
    "Would you press a button that pauses your aging but you watch everyone else grow old?",
    "Would you press a button that shows you your life's purpose but forces you to follow it?",
    "Would you press a button that lets you go back and fix one mistake but creates a new random one?",
    "Would you press a button that makes every day exciting but exhausting?",
    "Would you press a button that gives you more time but makes it feel slower?",
    "Would you press a button that lets you skip bad days but also randomly skips good ones?",
    "Would you press a button that makes you live twice as long but everything moves at half speed?",
    
    # Mental & Emotional Costs
    "Would you press a button that removes anxiety but also removes your caution?",
    "Would you press a button that makes you confident but delusional?",
    "Would you press a button that prevents sadness but also prevents deep joy?",
    "Would you press a button that makes you stop caring what people think but you become insensitive?",
    "Would you press a button that removes all negative emotions but makes you feel shallow?",
    "Would you press a button that gives you closure on everything but you can't move forward?",
    "Would you press a button that makes you fearless but reckless?",
    "Would you press a button that lets you control your emotions but they feel forced?",
    "Would you press a button that stops overthinking but you miss important details?",
    "Would you press a button that makes you happy all the time but nothing feels meaningful?",
    
    # Personal Growth Costs
    "Would you press a button that makes you instantly mature but you skip your youth?",
    "Would you press a button that gives you wisdom but you lose your sense of wonder?",
    "Would you press a button that fixes all your flaws but removes what makes you unique?",
    "Would you press a button that makes you always learn from mistakes but you feel every regret intensely?",
    "Would you press a button that makes you disciplined but spontaneity dies?",
    "Would you press a button that makes you successful but you can't enjoy the journey?",
    "Would you press a button that makes you grow faster but you outgrow everyone?",
    "Would you press a button that removes your insecurities but also your drive to improve?",
    "Would you press a button that makes you self-aware but hyper-critical?",
    "Would you press a button that fast-tracks your personal growth but it's painful?",
    
    # Truth & Reality Costs
    "Would you press a button that shows you the truth about everything but you can't share it?",
    "Would you press a button that makes you see people's true intentions but you can never trust again?",
    "Would you press a button that removes all lies from your life but ruins comfortable ignorance?",
    "Would you press a button that shows you your biggest flaw but you can't fix it?",
    "Would you press a button that makes you brutally honest but people avoid you?",
    "Would you press a button that shows you who talks about you but you can't confront them?",
    "Would you press a button that reveals all secrets but including your own?",
    "Would you press a button that shows you reality without filters but it's depressing?",
    "Would you press a button that makes you allergic to lies but people lie to spare you?",
    "Would you press a button that shows you who you'll become but you don't like it?",
    
    # Power & Control Costs
    "Would you press a button that lets you control one person but they control you back?",
    "Would you press a button that gives you power over time but everything else is random?",
    "Would you press a button that makes you lucky but someone close to you becomes unlucky?",
    "Would you press a button that lets you influence people but you can't be influenced?",
    "Would you press a button that makes you invincible but you feel no physical sensations?",
    "Would you press a button that gives you authority but everyone resents you?",
    "Would you press a button that lets you fix one global problem but you're blamed for the consequences?",
    "Would you press a button that gives you unlimited resources but you must share them?",
    "Would you press a button that makes you the smartest person but nobody understands you?",
    "Would you press a button that grants you influence but steals your privacy?",
    
    # Communication Consequences  
    "Would you press a button that makes you persuasive but you can't tell if people genuinely agree?",
    "Would you press a button that lets you speak any language but you stutter in your native one?",
    "Would you press a button that makes you witty but people don't take you seriously?",
    "Would you press a button that lets you always say the right thing but it never feels authentic?",
    "Would you press a button that prevents you from lying but also from keeping secrets?",
    "Would you press a button that makes your words powerful but you can't take them back?",
    "Would you press a button that lets you communicate telepathically but everyone can hear you too?",
    "Would you press a button that makes you a great listener but nobody listens to you?",
    "Would you press a button that lets you always win debates but people avoid talking to you?",
    "Would you press a button that makes you eloquent but you lose your casual speech?",
]
